### ISSUE TITLE
Add namespace to non-namespaced classes

### ISSUE THREAD

**Issue by matthieuauger** [humbug/php-scoper#10]
Currently the classes without namespace (for example https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php) are just ignored

**Comment by sebastianbergmann** [comment]
This is required for making php-scoper useful for PHPUnit.

**Comment by theofidry** [comment]
@sebastianbergmann is it still worth pursuing given that PHPUnit has now namespaces?

**Comment by sebastianbergmann** [comment]
Yes, this is still worth pursuing.

On the one hand, not all of PHPUnit's own code is namespaced yet (phpunit-mock-objects still has to be refactored). On the other hand, PHPUnit may depend on a component that does not use namespaces.

**Comment by padraic** [comment]
I would suggest allowing prefixing of non-NS code by configuration (of a name pattern perhaps), rather than it being the default behaviour.
