### ISSUE TITLE
[Question] Using autoloader inside the Scoper configuration file

### ISSUE THREAD

**Issue by alessandrotesoro** [humbug/php-scoper#1042]
Hi there,

I'm using php-scoper across multiple projects and part of the configuration file is always the same while other sections are manually adjusted. I put together a simple php class that does all the heavy lifting and generates the array used as configuration.

The problem I'm facing is that I can't use the composer's autoloader inside the scoper configuration, if I do, php-scoper seems to just generate a copy of the files into my destination folder but nothing is scoped. 

Here's a quick example:

```
<?php

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Finder\Finder;

return [
    'finders' => [
        Finder::create()
            ->files()
            ->ignoreVCS(true)
            ->notName('/LICENSE|.*\\.md|.*\\.dist|Makefile|composer\\.json|composer\\.lock/')
            ->exclude([
                'doc',
                'test',
                'test_old',
                'tests',
                'Tests',
                'vendor-bin',
            ])
            ->in(
				[
					'vendor/psr/container',
				]
			),
    ],
];
```

Removing this line:

```
require_once __DIR__ . '/../vendor/autoload.php';
```

Correctly scopes the files, however when the line is there it just makes a copy of the files.

Is this a know issue or the expected behavior?

**Comment by theofidry** [comment]
Hi!

It's a bit hard to tell to be honest. As far as PHP-Scoper is concerned, what it does is:

```php
$config = include $path;
```

One thing that may cause a surprise is that the working directory may change (if specified as an option `-d|--working-dir`).

>however when the line is there it just makes a copy of the files.

This make me thing the config returned is not the one you expect. It's hard to say without having more details about the code executed. I suggest you put a breakpoint or dump statement to check it out.

**Comment by theofidry** [comment]
Closing as there is nothing actionable here. If you encounter a concrete issue with a reproducer I can take a look at please open a new issue.
