### ISSUE TITLE
Add support for excluding files by type and/or excluding folders

### ISSUE THREAD

**Issue by weeblr** [humbug/php-scoper#1067]
## Feature Request

Hello,

While re-namespacing a library that includes a number of regexp stored in yaml files, I have found that php-scoper may apply some changes to these files, thus breaking the regexp.

From my reading of the docs, files can be excluded in scoper config using the "exclude-files" option, but that option only takes an actual list of individual files.

That's enough for a few files but in my case, there are several dozens of files across several directories. Managing the exclusions by hand is:
- a bit tedious :)
- brittle as future versions of the library may add more files which then need to be tracked and added to exclude-files

Would you consider: 
- allowing exclude-files to allow patterns, such as *.yaml, *.json?
- or add exclude-folders to exclude entire folders?
- or both as they don't solve the exact same problem

Also to be clear:

-  these files must be copied across (so can't exclude them with a Finder config). Simply, they must be left untouched.
- I currently fix the files with a patcher, it works and is generic but also likely brittle

Sorry if I missed a config option and this is already possible.

**Comment by theofidry** [comment]
Hi!

I think the easiest is that you collect the said fails, using whatever means (dumping the list and just collecting that list in the scoper file, or doing a custom find with the finder) and then forwarding them to with excluded files: https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#excluded-files.

The only caveat is that you need to keep in mind that PHP-Scoper will execute the `scoper.inc.php` file, so if you do something sketchy in there, e.g. autoloading an entire app, it may have undesired side-effects.

**Comment by weeblr** [comment]
Hi!

Thanks for your quick reply.

Like I said, I can already solved this with a patcher, by looking at the file extension (.yml in the case of that particular library I'm using) and revert the change made by php-scoper. It's 2 lines of PHP so that's not exactly hard.

In my case, I'm integrating  [Matomo Device-detector](https://github.com/matomo-org/device-detector). They have about 20 files in 3 folders.

Just feel it'd make sense for `exclude-files` to accept a pattern - or have ability to exclude entire folders. 

```
exclude-files: ['*.yml']

or

exclude-folders: ['device-detector/regexes']
```

This would save a fair bit of processing time, as these files can just be copied across untouched and of course it's safer. I'm sure the same would be useful for folders of .json, font files and other data files.

> so if you do something sketchy in there, e.g. autoloading an entire app,
This is just about specifying a list of files, from the source code of a library, there's no processing or loading an app.

**Comment by theofidry** [comment]
>Just feel it'd make sense for exclude-files to accept a pattern - or have ability to exclude entire folders.

Although not as pretty/convenient as you may want, you can do this:

```php

$excludedFiles = (static function () {
  return iterator_to_array(
    Finder::create()
      ->files()
      ->in('device-detector')
      ->name('*'),
  );
})();

return [
  'exclude-files' => $excludedFiles,
  // php-scoper config
];
```

or get the file names in there to match them against the regexes... Basically you can play around with the finder to get the file paths you want to exclude.

PHP-Scoper itself uses something like that: https://github.com/humbug/php-scoper/blob/main/scoper.inc.php#L15

**Comment by weeblr** [comment]
Thanks for the code sample, there are many ways indeed. All requiring code

>  Although not as pretty/convenient as you may want

So I guess extending exclude-files is not an option at the moment?

**Comment by theofidry** [comment]
>So I guess extending exclude-files is not an option at the moment?

I  prefer not to.

At least from PHP-Scoper and Box, in both I had to deal with regexes and finders and I always found it extremely messy, with people (myself included) having different expectations at different point in time. It's an area where it's hard to come up with a solution robust enough that please everyone, so I prefer to just provide the primitives (here the `Finder`) and let people handle it their way 😅

**Comment by weeblr** [comment]
Hi
OK, no problem. Thanks for your quick replies.

Cheers
