### ISSUE TITLE
Feature Request: Activate GitHub Discussions

### ISSUE THREAD

**Issue by hirasso** [humbug/php-scoper#1081]
## Feature Request

I'd like to ask a general question about more highlevel stuff and don't want to litter your issues with it :)

The "accepted answer" mechanism and visibility (as opposed to a closed issues) of discussions could also help others in the future that might have the same or similar questions.

Also: what an amazing project! ❤️

**Comment by theofidry** [comment]
Sure thing, it has now been enabled!
