### ISSUE TITLE
PHAR download link

### ISSUE THREAD

**Issue by sebastianbergmann** [humbug/php-scoper#113]
https://github.com/humbug/php-scoper#phar-preferred points to https://github.com/humbug/php-scoper/blob/master/releases which results in a 404.

And https://github.com/humbug/php-scoper/releases does not offer PHAR downloads.

**Comment by theofidry** [comment]
Nope indeed. @padraic could we set that up and do an auto-publish on release like done [there](https://github.com/api-platform/schema-generator/blob/master/.travis.yml#L41)?

**Comment by theofidry** [comment]
This should work now :)
