### ISSUE TITLE
Add it on Packagist

### ISSUE THREAD

**Issue by Soullivaneuh** [humbug/php-scoper#12]
I can't find `webmozart/php-scoper` on packagist, is that normal?

**Comment by webmozart** [comment]
The tool is not yet ready to be used, hence I didn't add it to Packagist yet.

**Comment by Soullivaneuh** [comment]
Any ETA for this? Do you need some help?

**Comment by webmozart** [comment]
@Soullivaneuh help would be much appreciated! Currently, the project ist stuck on #11.

**Comment by theofidry** [comment]
Will add it on packagist soon once there's a working version :)

**Comment by Soullivaneuh** [comment]
@theofidry Well, `dev-master` and `0.x` version are here for unstables states... :wink:

**Comment by theofidry** [comment]
@Soullivaneuh sure but there's not really any point into releasing something that doesn't do anything yet :P

As soon as #46 is done I think we're good for a first dev release. Anything before that is not really worth it as you wouldn't be able to scope something that has a composer dependency...

**Comment by theofidry** [comment]
The package has been released, we'll tag something as soon as we fixed #46
