### ISSUE TITLE
--no-ansi option has no effect

### ISSUE THREAD

**Issue by sebastianbergmann** [humbug/php-scoper#128]
I am working on integrating `php-scoper` into the build process for `phpunit.phar`. Here is the current state of the relevant section from PHPUnit's `build.xml`:
```xml
<exec executable="${basedir}/build/tools/php-scoper" taskname="php-scoper">
    <arg value="add-prefix" />
    <arg value="--no-ansi" />
    <arg value="--no-config" />
    <arg value="--no-interaction" />
    <arg value="--stop-on-failure" />
    <arg value="--output-dir" />
    <arg path="${basedir}/build/phar-prefixed" />
    <arg value="--prefix" />
    <arg value="PHPUnit" />
    <arg path="${basedir}/build/phar" />
</exec>
```
The progress bar is printed although the `--no-ansi` option is passed:
![screenshot from 2017-12-23 10-21-24](https://user-images.githubusercontent.com/25218/34318541-2d9a7cba-e7cb-11e7-9f32-901a854ead7d.png)
I am reluctant to pass `--quiet` as I am not sure whether that would also suppress error messages.

**Comment by theofidry** [comment]
>I am working on integrating php-scoper into the build process for phpunit.phar

Brillant, I would love to see that happening! :)

Regarding the issue I'll need to investigate this, I'm not sure if it's a PHP-Scoper issue or a Symfony one (maybe https://github.com/symfony/symfony/issues/23779).

I'll check the issue ASAP but Christmas and NY are a bit busy so don't expect much before mid-January. For the CI I think it's safe to use `--quiet`.

Regarding your PHP-Scoper integration, don't hesitate to report any hurdle with the process. Also I wonder if https://github.com/humbug/php-scoper/pull/117 would be of any help for that regard

**Comment by sebastianbergmann** [comment]
@theofidry Thank you for offer to help, I'll get back to you on that after the holidays. I had to revert https://github.com/sebastianbergmann/phpunit/commit/a19b93d75ab4901c03c8460fcab888cdb6339041 did work as well as I originally thought it did.

**Comment by theofidry** [comment]
Figures, I’m sure there will be a few cases that are not going to work out
of the box. But PhpScoper is not stable yet so doing changes to make sure
there is a smooth integration can be done

**Comment by theofidry** [comment]
`--no-ansi` seems to be working fine now. I reckon it was an issue in the Symfony Console
