### ISSUE TITLE
version shows hash

### ISSUE THREAD

**Issue by glensc** [humbug/php-scoper#130]
please make version show actual version. i downloaded 0.5.1, but it shows git hash:

```
[~/.local/bin/phars/phars (master)★] ➔ php71 ./php-scoper.phar --version
PHP Scoper version 600abecf9bd8ed8c02807c64529b9be4129b8b1e
```

**Comment by theofidry** [comment]
I wonder how but looks like I published the wrong artefact. I've checkout the tag and build the PHAR again, the publish one should be the good one now :)
