### ISSUE TITLE
Whitelist ignores yml files

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#224]
| Question    | Answer
| ------------| ---------------
| Box version | 0.8
| PHP version | 7.2.5
| Platform with version | Ubuntu

Thanks for the new "whitelist" feature! This setup great for classes, use imports etc. :+1: 

```php
return [
    'prefix' => 'RectorPrefixed',
    'whitelist' => [
        'Rector\*',
    ],
```

But it doesn't work for yml files. It should be ignored, but it's not.

```diff
 # services.yml
 services:
     _defaults:
         autowire: true

-    Rector\BetterPhpDocParser\:
+    RectorPrefixed\Rector\BetterPhpDocParser\:
         resource: '../'
```

**Comment by theofidry** [comment]
Isn't the whitelisting of YAML files done manually in rector? PHP-Scoper doesn't touch YAML files at all yet (it would be very nice to have though)

**Comment by TomasVotruba** [comment]
I'll check that. Still, in Symfony code handling Yaml is must have, otherwise we have to re-create whole php-scoper logic over again.

**Comment by theofidry** [comment]
I know, that's why https://github.com/humbug/php-scoper/issues/182 is there, but I couldn't work on it yet neither did I get any PR for it :)

**Comment by TomasVotruba** [comment]
I understand. Just to ping what's important :)

**Comment by theofidry** [comment]
Btw make sure to upgrade to 0.8.1, there was an autoloading issue with 0.8.0 with the whitelisting

**Comment by TomasVotruba** [comment]
Allright, thanks

**Comment by TomasVotruba** [comment]
You were right, the Bector build script handles prefixing yml files now: https://github.com/rectorphp/rector/blob/1dce10556526bd9c5d24ed49ccac5e0aaea814d6/bin/build-prefixed-rector.sh#L15

Shall continue in #182
