### ISSUE TITLE
Smarter string whitelisting

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#225]
When trying to scope Laravel standard edition, I saw several issues.

From SwiftMailer:

```php
    /**
     * Configure autoloading using Swift Mailer.
     *
     * This is designed to play nicely with other autoloaders.
     *
     * @param mixed $callable A valid PHP callable that will be called when autoloading the first Swift class
     */
    public static function registerAutoload($callable = null)
    {
        if (null !== $callable) {
            self::$inits[] = $callable;
        }
        spl_autoload_register(array('Swift', 'autoload'));
    }
```

The string `Swift` there could be scoped for this specific `spl_autoload_register` function. By default PHP-Scoper does not scope those as `foo('bar')` shouldn't be scoped (**[spec missing](https://github.com/humbug/php-scoper/tree/38b7155/specs/string-literal)**). But for a handful of functions like `spl_autoload_register()`, `class_exists()` & co, it does make sense.

**Comment by theofidry** [comment]
@TomasVotruba are you encountering this issue (which is fixable with custom patchers right now) for Rector/Simplify?

**Comment by TomasVotruba** [comment]
Not really, I use classic composer autoload

**Comment by theofidry** [comment]
I guess your codebase is clean enough to not have this issue 😄

**Comment by TomasVotruba** [comment]
I hope so :D
