### ISSUE TITLE
Add behat features to verify real output, and refactor handler a little bit

### ISSUE THREAD

**Issue by padraic** [humbug/php-scoper#24]
`AddPrefixCommandHandlerTest` tests both output and handler ops at same time (since that's what the handler is doing at the moment). Separating the concerns would probably translate into shorter unit tests, less fudging around with Symfony/Console in tests, and allow output to evolve separately.

**Comment by theofidry** [comment]
Being taken care of in https://github.com/humbug/php-scoper/pull/29

**Comment by theofidry** [comment]
Closed via #29
