### ISSUE TITLE
Please add phar and keys for new releases

### ISSUE THREAD

**Issue by willemstuursma** [humbug/php-scoper#248]
Using PHARs is the preferred way to download php-scoper.

However, the last phar is already a few releases back.

Can you add phars for the newer releases?

Probably the phar's should be created automatically using travis deploys.

**Comment by theofidry** [comment]
>Probably the phar's should be created automatically using travis deploys.

This is the case, but sometimes it fails :)

I'll trying to push for a new release soon which hopefully will be the beta or RC of 1.0.0. I'll make sure there will be a PHAR attached to that release

**Comment by BackEndTea** [comment]
If the deployment is done automatically through travis, triggering the build again may trigger the deployment again as well. (Not 100% sure if it works for this project, but it does work for a github pages deployment)

**Comment by theofidry** [comment]
It always depends of the kind of failure, in this case it requires changes in the `.travis.yml` (which have been fixed since then). So it would require a new release. I could always do so for 0.8.x, but I might as well jump straight to the new release, it's only a matter of weeks :)

**Comment by theofidry** [comment]
Done for https://github.com/humbug/php-scoper/releases/tag/0.9.1
