### ISSUE TITLE
Throw exception on invalid/unreadable path arguments

### ISSUE THREAD

**Issue by padraic** [humbug/php-scoper#25]
Currently the handler will silently skip invalid/non-existing paths or files.
Unreadable paths/files should already throw an Exception from using Symfony\Finder, but a test for that should be added.

**Comment by padraic** [comment]
Closed via #29

**Comment by theofidry** [comment]
@padraic actually I don't think it does: https://github.com/humbug/php-scoper/pull/29/files#diff-2a1a819937074698addbdf0b3e61ed1dR124

**Comment by theofidry** [comment]
On the same token we have https://github.com/humbug/php-scoper/issues/30.

I think we should dump the scoped files in a tmp directory. Interrupting the scoping will be easier that way.

**Comment by padraic** [comment]
@theofidry Agreed - the use case I see, is scoping into a ./build or similar and referencing that copy in a PHAR build config.

**Comment by theofidry** [comment]
Closed via #36
