### ISSUE TITLE
Guzzle not scoped correctly 

### ISSUE THREAD

**Issue by willemstuursma** [humbug/php-scoper#256]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | PHP Scoper version 0.9.99 (guess this is reported wrong by the .phar, it's 0.9.1)
| PHP version | 7.1
| Platform with version |  Ubuntu
| Github Repo | mollie/mollie-api-php

Our project depends on `guzzlehttp/guzzle`. 

We are running into an issue that `vendor/guzzlehttp/guzzle/src/functions_include.php` is scoped correctly, but `vendor/guzzlehttp/psr7/src/functions_include.php` is *not*. 

This script reproduces the problem:

```
wget -q https://github.com/humbug/php-scoper/releases/download/0.9.1/php-scoper.phar
wget -q https://github.com/humbug/php-scoper/releases/download/0.9.1/php-scoper.phar.pubkey

composer require guzzlehttp/guzzle
php -f php-scoper.phar add-prefix
```

Then, observe these two files:

`cat build/vendor/guzzlehttp/guzzle/src/functions_include.php`

```php
<?php

namespace _PhpScoper5b6c08b28cf1a;

// Don't redefine the functions if included multiple times.
if (!\function_exists('_PhpScoper5b6c08b28cf1a\\GuzzleHttp\\uri_template')) {
    require __DIR__ . '/functions.php';
}
```

`cat build/vendor/guzzlehttp/psr7/src/functions_include.php` 

```php
<?php

namespace _PhpScoper5b6c08b28cf1a;

// Don't redefine the functions if included multiple times.
if (!\function_exists('GuzzleHttp\\Psr7\\str')) {
    require __DIR__ . '/functions.php';
}
```

Note that the second file does not have the namespace added to the `function_exists` call. This causes the require not to be executed.

**Comment by willemstuursma** [comment]
There's no config used:

```bash
vagrant@mollie:/var/www/mollie/tmp/scoper-issue$ ls -lsa
total 612
  4 drwxrwxr-x  8 502 dialout    272 Aug  9 11:06 .
  4 drwxr-xr-x 83 502 dialout   2822 Aug  9 09:24 ..
  4 drwxrwxr-x  7 502 dialout    238 Aug  9 11:06 build
  4 -rw-rw-r--  1 502 dialout     63 Aug  9 09:25 composer.json
 12 -rw-rw-r--  1 502 dialout   8224 Aug  9 09:25 composer.lock
576 -rw-rw-r--  1 502 dialout 588058 Aug  6 18:19 php-scoper.phar
  4 -rw-rw-r--  1 502 dialout    800 Aug  6 18:19 php-scoper.phar.pubkey
  4 drwxrwxr-x  6 502 dialout    204 Aug  9 09:25 vendor
vagrant@mollie:/var/www/mollie/tmp/scoper-issue$ php -f php-scoper.phar add-prefix --no-config --force


    ____  __  ______     _____
   / __ \/ / / / __ \   / ___/_________  ____  ___  _____
  / /_/ / /_/ / /_/ /   \__ \/ ___/ __ \/ __ \/ _ \/ ___/
 / ____/ __  / ____/   ___/ / /__/ /_/ / /_/ /  __/ /
/_/   /_/ /_/_/       /____/\___/\____/ .___/\___/_/
                                     /_/

PHP Scoper version 0.9.99

 113/113 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] Successfully prefixed 113 files.


 // Memory usage: 9.54MB (peak: 18.06MB), time: 3.24s

vagrant@mollie:/var/www/mollie/tmp/scoper-issue$ cat build/vendor/guzzlehttp/psr7/src/functions_include.php
<?php

namespace _PhpScoper5b6c20258ef12;

// Don't redefine the functions if included multiple times.
if (!\function_exists('GuzzleHttp\\Psr7\\str')) {
    require __DIR__ . '/functions.php';
}
vagrant@mollie:/var/www/mollie/tmp/scoper-issue$

**Comment by willemstuursma** [comment]
Thanks! I really appreciate it!

**Comment by willemstuursma** [comment]
BTW @theofidry there is an official regex on the PHP.net site for what constitutes a class name: 

> Variable names follow the same rules as other labels in PHP. A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'

The current implementation does not support UTF-8 classnames.

**Comment by theofidry** [comment]
Thanks I didn't know about it, from what I see we should be good then :).

>The current implementation does not support UTF-8 classnames.

it does, `p{L}` with the `u` (unicode) flag matches any kind of letter in any language, so it's a cleaner equivalent of `[a-zA-Z\x7f-\xff]`

**Comment by willemstuursma** [comment]
👍 thanks for looking into it
