### ISSUE TITLE
[PHAR] Sign PHAR

### ISSUE THREAD

**Issue by sebastianbergmann** [humbug/php-scoper#307]
Please consider signing your PHAR with a GPG key and publish that signature alongside the signed PHAR so that `--force-accept-unsigned` is not required when using Phive.

**Comment by theofidry** [comment]
It's been on my todo list for a while, I hope to get to it soon enough :)

**Comment by sebastianbergmann** [comment]
Any update on this? Thanks!

**Comment by theofidry** [comment]
I'll try to check it out with the next release for which I would like to merge https://github.com/humbug/php-scoper/pull/318

**Comment by sebastianbergmann** [comment]
Any update on this? Thanks!

**Comment by theofidry** [comment]
Note to self: do this for the next release which fully supports PHP 7.4 & Composer 2

https://phar.io/howto/sign-and-upload-to-github.html

**Comment by theofidry** [comment]
Does as of 0.17.6. Just missing the PR to phive

**Comment by theseer** [comment]
Merged.

You might have to run `phive update-repository-list` to fetch the latest version of the repo meta data file.
