### ISSUE TITLE
PEAR-style non-namespaced PSR-0 class not available in autoloader

### ISSUE THREAD

**Issue by muglug** [humbug/php-scoper#308]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.6.0
| PHP version | 7.3
| Platform with version | MacOS 10.13.16
| Github Repo | - https://github.com/vimeo/psalm

### Reproduction

Run

```
composer bin box install
vendor/bin/box --debug compile
```

Notice the `autoload_classmap.php` in `.box_dump` is missing an entry for `JsonMapper` (but has other entries).

This class isn't used in Psalm-proper, but it is used in Psalm's language server (which @greg0ire is working to enable in the phar via a `--language-server` flag)

Here's the (hopefully temporary) hack I'm using to work around it: https://github.com/vimeo/psalm/compare/phar-compat#diff-feb180cea6e9d88bcfcbbbf7addc6efaR25

**Comment by theofidry** [comment]
I'm a bit surprised by that: is that class properly listed in the `composer.json`? The `autoload_classmap.php` is an artefact of Composer which Box doesn't alter (it only appends stuff to the `autoload.php` for PHP-Scoper)

**Comment by greg0ire** [comment]
It does not seem to be, but why should it: https://github.com/cweiske/jsonmapper/blob/master/composer.json#L6 ? What's peculiar here is that psr-0 is in use.

**Comment by muglug** [comment]
The class is listed in https://github.com/felixfbecker/php-advanced-json-rpc/blob/aaaf9b6088b9149ece1bf0e5f690976506bbdadf/composer.json#L24 which, in turn, is required by Psalm

**Comment by theofidry** [comment]
Ah wait, IIRC PHP-Scoper needs to transform the PSR-0 to PSR-4: https://github.com/humbug/php-scoper/blob/bb5eb48/tests/Scoper/Composer/JsonFileScoperTest.php.

There is however edge cases of PSR-0 which are not portable to PSR-4

**Comment by muglug** [comment]
JsonMapper.php has two docblocks, and ends with `?>` - maybe that makes it an edge-case?

**Comment by theofidry** [comment]
I doubt that. I think it's more a matter of the correctness of the conversion between PSR-0 & PSR-4. You should be able to double check it in the dumped scoped PHAR (or the `box_dump`).

**Comment by muglug** [comment]
What am I looking for? It's here: https://gist.github.com/muglug/dcf0c528a10d24a93b02313b7afe269d

**Comment by theofidry** [comment]
I think the issue here is not the scoped class itself, but what the Composer autoloading configuration is for it (the _scoped_ autoloading configuration, so `installed.json`). Note that it may be excluded from `box_dump` if the Composer files are set to excluded

**Comment by muglug** [comment]
How can I include that file in the dumped output? (it isn't atm)

**Comment by theofidry** [comment]
Setting this setting to false: https://github.com/humbug/box/blob/master/doc/configuration.md#excluding-the-composer-files-exclude-composer-files

**Comment by muglug** [comment]
It's in `installed.json` and also `composer.lock`

installed.json:
```
    {
        "name": "netresearch\/jsonmapper",
        "version": "v1.4.0",
        "version_normalized": "1.4.0.0",
        "source": {
            "type": "git",
            "url": "https:\/\/github.com\/cweiske\/jsonmapper.git",
            "reference": "3868fe1128ce1169228acdb623359dca74db5ef3"
        },
        "dist": {
            "type": "zip",
            "url": "https:\/\/api.github.com\/repos\/cweiske\/jsonmapper\/zipball\/3868fe1128ce1169228acdb623359dca74db5ef3",
            "reference": "3868fe1128ce1169228acdb623359dca74db5ef3",
            "shasum": ""
        },
        "require": {
            "php": ">=5.6"
        },
        "require-dev": {
            "phpunit\/phpunit": "~4.8.35 || ~5.7 || ~6.4",
            "squizlabs\/php_codesniffer": "~1.5"
        },
        "time": "2017-11-28T21:30:01+00:00",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-4": {
                "_HumbugBoxee3c5b94b93b\\JsonMapper\\": "src\/JsonMapper\/"
            }
        },
        "notification-url": "https:\/\/packagist.org\/downloads\/",
        "license": [
            "OSL-3.0"
        ],
        "authors": [
            {
                "name": "Christian Weiske",
                "email": "cweiske@cweiske.de",
                "homepage": "http:\/\/github.com\/cweiske\/jsonmapper\/",
                "role": "Developer"
            }
        ],
        "description": "Map nested JSON structures onto PHP classes"
    }
```

composer.lock:
```
    {
            "name": "netresearch/jsonmapper",
            "version": "v1.4.0",
            "source": {
                "type": "git",
                "url": "https://github.com/cweiske/jsonmapper.git",
                "reference": "3868fe1128ce1169228acdb623359dca74db5ef3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/cweiske/jsonmapper/zipball/3868fe1128ce1169228acdb623359dca74db5ef3",
                "reference": "3868fe1128ce1169228acdb623359dca74db5ef3",
                "shasum": ""
            },
            "require": {
                "php": ">=5.6"
            },
            "require-dev": {
                "phpunit/phpunit": "~4.8.35 || ~5.7 || ~6.4",
                "squizlabs/php_codesniffer": "~1.5"
            },
            "type": "library",
            "autoload": {
                "psr-0": {
                    "JsonMapper": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "OSL-3.0"
            ],
            "authors": [
                {
                    "name": "Christian Weiske",
                    "email": "cweiske@cweiske.de",
                    "homepage": "http://github.com/cweiske/jsonmapper/",
                    "role": "Developer"
                }
            ],
            "description": "Map nested JSON structures onto PHP classes",
            "time": "2017-11-28T21:30:01+00:00"
        },
```

**Comment by muglug** [comment]
(thanks for helping, by the way - this is above and beyond)

**Comment by muglug** [comment]
OH I think I understand it?

`installed.json` is wrong.

```
        "autoload": {
            "psr-4": {
                "_HumbugBoxee3c5b94b93b\\JsonMapper\\": "src\/JsonMapper\/"
            }
        }
```

is definitely untrue, as the layout of the folder is
```
src/
 - JsonMapper/
    - Exception.php (class JsonMapper_Extension)
 - JsonMapper.php
```

**Comment by muglug** [comment]
I think it _should_ be
```
        "autoload": {
            "psr-0": {
                "_HumbugBoxee3c5b94b93b\\JsonMapper": "src/"
            }
        },
```

**Comment by muglug** [comment]
It looks like the original PR [only tested PSR-0 classes in namespaces](https://github.com/humbug/php-scoper/commit/32a90342efcf0b0b2419b24ae2509e25e78d77e5) - I'll try to create a breaking testcase

**Comment by theofidry** [comment]
Can't JsonMapper be upgraded to PSR-4?

**Comment by muglug** [comment]
Well, because it's a dependency of a dependency I don't have much control there.

**Comment by muglug** [comment]
I believe this is valid PSR-0:

> Under the psr-0 key you define a mapping from namespaces to paths, relative to the package root. *Note that this also supports the PEAR-style non-namespaced convention.*

**Comment by muglug** [comment]
The break happens due to this composer classloader code:

```
        // PSR-0 lookup
        if (false !== $pos = strrpos($class, '\\')) {
            // namespaced class name
            $logicalPathPsr0 = substr($logicalPathPsr4, 0, $pos + 1)
                . strtr(substr($logicalPathPsr4, $pos + 1), '_', DIRECTORY_SEPARATOR);
        } else {
            // PEAR-like class name
            $logicalPathPsr0 = strtr($class, '_', DIRECTORY_SEPARATOR) . $ext;
        }
```

Adding the prefix prevents the `PEAR-like class name` else being hit.

**Comment by theofidry** [comment]
So it's not easily fixable, but I believe at the very least a doc entry could be added in the list of PHP-Scoper's shortcomings a few possible alternative solutions

**Comment by BackEndTea** [comment]
I must say i completely forgot about 'old style' PSR-0 during that PR
