### ISSUE TITLE
[Command] Add a filter option to limit which files are scoped

### ISSUE THREAD

**Issue by Wouter0100** [humbug/php-scoper#311]
## Feature Request

Currently, when running add-prefix it always adds prefixes everything. In a building pipeline this is the desired behavior, but this is after development. While developing I unfortunately also require add-prefix before I'm able to test/use it in the development environment. 

In my current setup I have a file watcher (PHPStorm) which runs `add-prefix` every time something changes, and upload the differences between the last prefix-run and the current prefix-run to my development environment. For large projects, this takes a while (the `add-prefix` run, to be exact - the uploading doesn't, as that is only one file most of the time).

Because of this, I'd like to suggest a feature request to - for example - add a `--limit {path}` argument to `add-prefix`, which would limit the scoping to this specific file or folder, without making alterations to the finders.

**Comment by theofidry** [comment]
That's a reasonable feature IMO, PRs are welcome :)

**Comment by theofidry** [comment]
Renamed the title. I think this could go with a `--filter` option. All files defined are still copied, but only the filtered one are actually scoped. From a config PoV it is equivalent to do something like this:

```php
'whitelist-files' => (static function () { return Finder::create()->in($dir)->files(); })(),
```

I am unsure how it should be handled under the hood: whether it should make use of `whitelist-files` or something else though

**Comment by Wouter0100** [comment]
Hmm, I think I not really described the feature request clearly. 

```All files defined are still copied, but only the filtered one are actually scoped.```
This is exactly the thing that's not really desired, that all files are still copied. Especially in larger projects and during development, it would be good to only scope and copy the file specified. This way we're able to run inotify (or the PHPStorm file watcher) and run PHP-Scoper only on that file, to reduce the scope time.

**Comment by theofidry** [comment]
A problem I can see is that scoping a file is not a self contained process: depending of the excluded and exposed symbols configuration this will have side effects such as requiring to dump the autoloader again.

If performance is an issue, it might be worth considering using Box for the scoping instead as it has parallelisation abilities. If the desired output is not a PHAR, you can still extract the produced PHAR into a directory and use that.

**Comment by theofidry** [comment]
After reviewing it, in light of the last development cycles, I do not see how this could be working except for a very specific edge case where Composer is not used at all. Indeed scoping  a singular file has an impact in the autoloader and cannot (easily) be applied alone.

So I will be closing this. If you or someone else has an idea and want to propose something that work, feel free to open an issue or a draft PR I'll be happy to review it.

**Comment by theofidry** [comment]
Not entirely unrelated though getting the scopped content of the singular file can be done with #771. But I don't think it will completely fit that use case still.
