### ISSUE TITLE
PHP 7.1 and dependencies

### ISSUE THREAD

**Issue by Narno** [humbug/php-scoper#319]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.11.4
| PHP version | 7.1
| Platform with version | All
| Github Repo | https://github.com/Cecilapp/Cecil/

Hello,

I notice version `0.11.4` works with **PHP 7.1**, and requires `roave/better-reflection: ^3.0`.
So:
- BetterReflection 3.3.0 works with PHP 7.1
- BetterReflection 3.4.0 requires PHP 7.2

The problem is when I try to install `humbug/box` 3.7.0 Composer install `humbug/php-scoper` 0.11.4 and try to install `roave/better-reflection` 3.4.0: it can't because PHP 7.2 is required.

See https://travis-ci.com/Cecilapp/Cecil/jobs/198598536.

I think `php-scoper` 0.11.4 should requires `roave/better-reflection: ^3.3.0` insteand of `^3.0`.

(Not sure my explanation is clear ^^').

**Comment by Narno** [comment]
Temporary workaround (force `roave/better-reflection` version):
```json
"require": {
  "php": "^7.1"
  [...]
},
"require-dev": {
  "humbug/box": "3.7.0",
  "roave/better-reflection": "3.3.0"
}
```

**Comment by theofidry** [comment]
It's a bit weird, shouldn't composer pick up `3.3.0` since it satisfies both the PHP and the `^3.0.0` constraints?

**Comment by BackEndTea** [comment]
If you need your package/project to install php 7.1 compatible packages you can add the following to your `composer.json`
```json
    "config": {
        "platform": {
            "php": "7.1.3"
        }
    }
```

This will force composer to see your php version as php 7.1.3. 
I'd advice to use 7.1.3 or higher because some major packages have that as their minimum (symfony 4 for example)

**Comment by Narno** [comment]
>It's a bit weird, shouldn't composer pick up 3.3.0 since it satisfies both the PHP and the ^3.0.0 constraints?

That's the question! :stuck_out_tongue_winking_eye:

Thanks for the tips @BackEndTea! :+1:
