### ISSUE TITLE
class_alias breaks if class exists

### ISSUE THREAD

**Issue by muglug** [humbug/php-scoper#336]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.8
| PHP version | 7.3.5
| MacOs
| Github Repo | - https://github.com/vimeo/psalm

PHP Scoper slightly breaks [this polyfill for `JsonException`](https://github.com/symfony/polyfill-php73/blob/d1fb4abcc0c47be136208ad9d68bf59f1ee17abd/Resources/stubs/JsonException.php).

It gets a `class_alias` appended (as expected), but that `class_alias` causes a warning when running on PHP 7.3 as PHP 7.3 includes the class.

```php
\class_alias('_HumbugBoxc9de1eddd699\\JsonException', 'JsonException', \false);
```

I'm currently fixing it in Psalm's build with [this hideous patch](https://github.com/vimeo/psalm/blob/b13eaa20d279e37bc5083bde749147c3265f40df/bin/improve_class_alias.php) that wraps a `class_exists` check around the `class_alias`:

```php
if (!\class_exists(\JsonException::class, false)) {
    \class_alias('_HumbugBox9de1eddd699\\JsonException', 'JsonException', \false);
}
```

**Comment by theofidry** [comment]
Hm I see, do you think all those class aliases should be wrapped in a `class_exists()` statement like you did?

**Comment by muglug** [comment]
Yeah, I think so

**Comment by theofidry** [comment]
Hm wait: how come that `JsonException` is whitelisted in the first place?
