### ISSUE TITLE
Wildcards for whitelisting files

### ISSUE THREAD

**Issue by mundschenk-at** [humbug/php-scoper#348]
## Feature Request

I'd like to be able to whitelist "partials" (i.e. partial HTML templates) in dependencies, without specifying each individual filename. It would be nice if this was possible using wildcards, like this:

```php
    'files-whitelist' => [
        '<path>/partials/*.php',
        '<otherpath>/<somefile>.php',
    ],
```

**Comment by theofidry** [comment]
What you can do is implement that yourself:

```php
<?php

// scoper.inc.php 

function get_files_whitelist(): array {...}

return [
    // ...
    'files-whitelist' => get_files_whitelist(),
];
```

The only thing is that you need to be very careful of the dependencies you are using if you are relying on any external code. Also note that you already have access to the Symfony Finder (it's under a different namespace but in the end it's just a scoped version of it):

```php
use Isolated\Symfony\Component\Finder\Finder;
```

**Comment by theofidry** [comment]
Closing as there is a workaround for now. If one needs a better integrated feature I'll be happy to accept a PR or provide help to implement it.
