### ISSUE TITLE
Array annotations are ignored

### ISSUE THREAD

**Issue by pavel-mailpoet** [humbug/php-scoper#350]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 0.11.4 
| PHP version | 7.1.23
| Platform with version | e.g. MacOS

I am trying to use php-scoper for Doctrine. It works in most cases, but it ignores their array style annotations. Doctrine does this:
``` 
   /**
     * @var array<\Doctrine\ORM\Mapping\Index>
     */
    public $indexes;
```
php-scoper unfortunatelly doesn't find such annotation and leaves the namespace unchanged.

**Comment by theofidry** [comment]
Actually PHP-Scoper doesn't check the phpdocs at all, so I wouldn't indeed expect it to work

**Comment by pavel-mailpoet** [comment]
Fair Enough. Doctrine is using phpdocs so I had to write my own script that is replacing those.
