### ISSUE TITLE
Disable the aliasing of prefixed classes

### ISSUE THREAD

**Issue by polevaultweb** [humbug/php-scoper#352]
I might have not read the manual correctly here but I'm looking for a way to turn off the aliasing for classes.

For example, I'm prefixing the Google SDK in my WordPress plugin and some of the classes in the SDK don't use a namespace. But after prefixing, my namespace is added. However, if another plugin bundles the SDK as it is, my `scoper-autoload.php` aliases the classes without a namespace to my namespace:

`\class_alias('MyNamespace\\Google_Client', 'Google_Client', \false);`

 Which means the other plugin will incorrectly use my version of the SDK (it does a class exists check before loading it's files).

Can I turn off the class_alias functionality? Many thanks for a great library btw 👍

**Comment by theofidry** [comment]
The class alias should only work as part of the whitelist mechanism (more details [here](https://github.com/humbug/php-scoper#whitelist)). So if you were to not whitelist those no class alias should be created

**Comment by polevaultweb** [comment]
@theofidry thanks for that, i clearly hadn't read the manual 🤦‍♂
