### ISSUE TITLE
How exactly whitelist works for subnamespaces?

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#366]
I'm trying to create prefixed `ecs.phar`:

```php
<?php declare(strict_types=1);

// scoper.inc.php
return [
    'whitelist' => [
        'Symplify\EasyCodingStandard\*',
        #  this might work, but it's too broad
        # 'Symplify\*',
    ],
];
```

But it prefixed the namespace in the file :/

```diff
 services:
-    Symplify\EasyCodingStandard\:
+    _HumbugBox1de09932b74e\Symplify\EasyCodingStandard\:
```

What can I do to remove it?

**Comment by TomasVotruba** [comment]
I tried this with same effect:

```yaml
    'whitelist' => [
        'Symplify\EasyCodingStandard\*',
        'Symplify\EasyCodingStandard*',
        'Symplify\EasyCodingStandard',
        'Symplify\CodingStandard\*',
        'Symplify\CodingStandard',
        'PHP_CodeSniffer\*',
        'PhpCsFixer\*',
    ],
```

Here is the full PR with box and scoper: https://github.com/Symplify/Symplify/pull/1734

**Comment by theofidry** [comment]
>But it prefixed the namespace in the file :/

Is it in the PHP file or just the service declaration? I would be surprised if the namespace whitelisting doesn't work properly, so I have higher suspicious of it not being done correctly for the Symfony service declaration files

**Comment by TomasVotruba** [comment]
It's only prefixed in the config, that's why the class cannot be found.

**Comment by theofidry** [comment]
Arg indeed https://github.com/humbug/php-scoper/blob/master/src/Scoper/Symfony/YamlScoper.php doesn't make use of the whitelist at all to check that... Probably the same for the XML one

**Comment by theofidry** [comment]
Correction: the YamlScoper does take that into account, the issue is with the logic itself. This scoper tries to go by regexes which I guess has its limitations... Maybe it's still possible to do so with it but I'm struggling a bit to do so
