### ISSUE TITLE
Feature request for Nette .neon support

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#376]
Is basically the same as prefixing Symfony .yml files, just configs have different structure. I provide examples convering configs, to it make clear:

```diff
 rules:
-    - PHPStan\Rules\Arrays\DuplicateKeysInLiteralArraysRule
+    - Prefix\PHPStan\Rules\Arrays\DuplicateKeysInLiteralArraysRule

 services:
     -
-        class: PHPStan\Rules\Classes\ExistingClassInInstanceOfRule
+        class: Prefix\PHPStan\Rules\Classes\ExistingClassInInstanceOfRule

     -
-        factory: @PHPStan\Rules\Classes\ExistingClassInInstanceOfRule
+        factory: @Prefix\PHPStan\Rules\Classes\ExistingClassInInstanceOfRule

 extensions:
-    rules: PHPStan\DependencyInjection\RulesExtension
+    rules: Prefix\PHPStan\DependencyInjection\RulesExtension
```

Now the `*.neon` files are skipped without a touch.

**Comment by TomasVotruba** [comment]
This is not relevant anymore or working.

For future debugging/feature, this is how *.neon scoping works in phpstan, that runs on neon with DI:
https://github.com/phpstan/phpstan-src/blob/ded4467c8f44376da2d9edf96d3bb60dcb2cd148/compiler/build/scoper.inc.php#L98-L139

**Comment by theofidry** [comment]
Let's keep it open then, it's still a nice to have and would solve PHPStan case as well

**Comment by TomasVotruba** [comment]
Sure, just open it as standalone issue. I use issues to maintain my to-do list and I want it clean.

Thanks you
