### ISSUE TITLE
How to scope only user-defined namespaces?

### ISSUE THREAD

**Issue by AndriyHudyma** [humbug/php-scoper#378]
Hi! Is there an easy way to scope only those namespaces that are user-defined?
In another words, currently we have a feature that allows to scope "all namespaces, with exception of those that are on the list"
Is there a feature to scope "no namespaces, but only those that are on the list"?
Thanks!

**Comment by theofidry** [comment]
Hi!

>Is there a feature to scope "no namespaces, but only those that are on the list"?

Not really, because the goal is to scope as much as possible not vice-versa.

>Is there an easy way to scope only those namespaces that are user-defined?

I'm not sure to understand that part: any non-core code _is_ user-defined and the non-core code should not be scoped already

**Comment by AndriyHudyma** [comment]
Thanks for your response!

Let me describe the use case when we need to scope only listed namespaces.

A plugin for CMS system: 
1) Can use some dependencies from that CMS taking them from /vendor folder located in root folder of the project.
2) Can have its own namespaces.
3) Can have its own dependencies located in local (plugin specific) /vendor folder.

There could be multiple plugins and we would like to ensure that there are no namespaces collision.
We don't need to scope dependencies from CMS, because they are unique.
We don't need to scope our plugin own namespaces, because they have unique plugin vendor prefix.
But we need to scope plugin's dependencies, because it could happen that two different plugins using the same package.
That's were 'scope only listed namespaces' feature can help. Or scope 'only namespaces from specified vendor folder' feature.

Of course, there is another way - just scope all namespaces. This will work. However, what if all plugins are using some heavy package that already present in CMS anyway? Like Laravel's Eloquent. We will need to put that package in each plugins vendor folder, which is not ideal.

**Comment by matzeeable** [comment]
Yeah, this feature request is also needed for WordPress plugin environment. I want to add PHP-Scoper to my open-source project [WP React Starter](https://github.com/devowlio/wp-react-starter). I want to prefix only a given list of namespaces so e. .g WordPress functions and classes are not prefixed. Is this somehow possible?

**Comment by theofidry** [comment]
@matzeeable sorry for the late reply. It is not currently possible but should be doable via https://github.com/humbug/php-scoper/issues/303#issuecomment-614097867

**Comment by leoloso** [comment]
This is possible by passing a regex with a negative lookahead to `exclude-namespaces`, that will match all namespaces except the ones you want to prefix.

For instance, this will prefix only `NamespaceA` and `NamespaceB`:

```php
return [
  'prefix' => 'MyPrefix',
  'finders' => [
      // ...
  ],
  'exclude-namespaces' => [
      '/^(?!.*(NamespaceA|NamespaceB))/',
  ],
];
```
