### ISSUE TITLE
Native WordPress functions don't work

### ISSUE THREAD

**Issue by vielhuber** [humbug/php-scoper#380]
| Question    | Answer
| ------------| ---------------
| Box version | 0.13.1
| PHP version | 7.3.12
| Platform with version | Windows WSL

I use php-scoper inside my own wordpress plugin.

However when using a native WP function inside my plugin (like update_option), I get the error:

```
Fatal error: Uncaught Error: Call to undefined function _PhpScoper530411ca8549\update_option()
```

php-scoper spits out the following code:

```php
namespace _PhpScoper530411ca8549;
require_once __DIR__ . '/vendor/autoload.php';
\_PhpScoper530411ca8549\update_option('foo', 'bar');
```

Since update_option is not inside the namespace of the plugin (and comes outside from wordpress), this cannot work, or am I wrong?

Fiddling around with whitelist-global-functions doesn't change this behaviour.

Can you please help out? How do I exclude native wordpress functions from prefixing or even get them running with prefixing?

**Comment by vielhuber** [comment]
I fixed this with:

- Add a namespace ```MyCustomPlugin``` to my WordPress plugin file
- Add ```'whitelist' => ['MyCustomPlugin\*']``` to scoper.inc.php to exclude all global functions called in this file.

**Comment by theofidry** [comment]
@vielhuber to me it looks like you are missing the `scoper-autoload.php` file which is critical for any sort of whitelisting

**Comment by vielhuber** [comment]
I included scoper-autoload.php. The problem is, that WordPress is outside of php-scopers influence.

**Comment by theofidry** [comment]
Saw #303, I'll try to have a look to see if there is anything to change there
