### ISSUE TITLE
Hotloaded globally available functions from dependency are not prefixed in subnamespace

### ISSUE THREAD

**Issue by vielhuber** [humbug/php-scoper#383]
Hello!

I use dependencies that hotload functions via the composer.json file.

That means: There are globally defined functions available, which I use throughout the codebase.

php-scoper prefixes:
- the dependency file (inside the vendor folder), where the global functions are defined. Here the new namespace "ScopedTest" gets added.
- files in my codebase without any namespace (they then get the namespace ScopedTest). inside those files, the globally used functions are correctly prefixed (with "ScopedTest").

The problem now is:

If I have a file in my codebase with a namespace (for example SomeNamespace), this file then gets the new namespaced "ScopedTest\SomeNamespace". However, all used global functions inside that file are not prefixed anymore!

Can somebody please explain that behaviour?

**Comment by vielhuber** [comment]
Example:

**hotloaded-functions.php**
```php
<?php
// no namespace here
function foo() { echo 'foo'; }
```

**main-code-without-namespace.php**
```php
<?php
require_once('hotloaded-functions.php');
foo(); // works!
```
**main-code-with-namespace.php**
```php
<?php
namespace MainCode;
require_once('hotloaded-functions.php');
foo(); // works
```

And now after running php-scoper:

**hotloaded-functions.php**
```php
<?php
namespace _PhpScoper691289775f95;
// no namespace here(!)
function foo() { echo 'foo'; }
```

main-code-without-namespace.php
**```php**
<?php
namespace _PhpScoper691289775f95;
require_once 'hotloaded-functions.php';
\_PhpScoper691289775f95\foo(); // works
```

**main-code-with-namespace.php**
```php
<?php
namespace _PhpScoper691289775f95\MainCode;
require_once 'hotloaded-functions.php';
foo(); // does not work!
```

**Comment by vielhuber** [comment]
One way to solve this would be to use ```\foo();``` instead of ```foo();```.
But I don't want to change all functions in my source code.

**Comment by theofidry** [comment]
Hi!

You probably want to have a look at https://github.com/humbug/php-scoper#implementation-insights. TL:DR; so far PHP-Scoper assumes all the functions you are using are autoloaded by your project. See https://github.com/humbug/php-scoper/issues/367 for a related issue when dealing with Wordpress functions

**Comment by theofidry** [comment]
Oh I missed your comments: one issue that I see I think is the lack of autoloader. PHP-Scoper really assumes you are using Composer. Maybe it can work without, but I did not try to check or investigate

**Comment by vielhuber** [comment]
The functions are hotloaded via composer (https://getcomposer.org/doc/04-schema.md#files), I just used the above example to illustrate the behaviour (it's exactly the same).

The thing is: Why does php-scoper not prefix global functions (that are autoloaded via composer and which have no namespace in its declaration file) inside a namespace?

**Comment by theofidry** [comment]
It should as long as they are not internal symbols: https://github.com/humbug/php-scoper/blob/master/specs/function/global-scope-global-func.php#L31

**Comment by vielhuber** [comment]
In the test file you don't specify a namespace in the source as I understand.
The problem only arises, if a namespace is used and the global functions are defined without a namespace (see example above).

**Comment by theofidry** [comment]
Ah, indeed: https://github.com/humbug/php-scoper/blob/master/specs/function/namespace-global-func.php#L33

IIRC it's simply because it's not possible. There is no way to know if that function is `main()` or `A\main()`. So you either have to prefix with `\` or more elegant, `use function main;`.

**Comment by vielhuber** [comment]
Thank you very much, that explains the whole thing.
