### ISSUE TITLE
[Scoper] scoper-autoload.php is dumped in the wrong `vendor` directory

### ISSUE THREAD

**Issue by jarrodbell** [humbug/php-scoper#384]
One of the libraries I am installing via composer has its own 'vendor' folder.

The library I am using is called [carbon-fields](https://github.com/htmlburger/carbon-fields/), which creates a folder 'vendor/htmlburger/carbon-fields/packages/vendor'.

The final output of php-scoper 'scoper-autoload.php' is always getting output to that folder, rather than the root 'vendor' folder.

This seems to be the offending line:
https://github.com/humbug/php-scoper/blob/1275a483b3cf3a06245bb0eab5763bde73a5a72e/src/Console/Command/AddPrefixCommand.php#L229

Perhaps the `usort` call just above this line should be comparing `return strlen($a) <=> strlen($b);` so that it get the shortest path, rather than the longest?

**Comment by theofidry** [comment]
If that works and don't break anything else sure :)

**Comment by jarrodbell** [comment]
What was the intent of using the longest path? Unless I am reading the code incorrectly? I assume using the shortest path was the intent, so this would be a bug that you could fix and make a new release? I am only new to this library so didn't want to submit a pull request without understanding the code well enough.

In my tests changing that usort line worked and the scoper-autoload.php file was output in the correct directory.

**Comment by theofidry** [comment]
I don't recall if there was a reason :/ But if there is one it should be capture by the PHP-Scoper test suite

**Comment by theofidry** [comment]
It is not clear if there is a valid reason for this, so I would suggest proposing a PR with the change and see if any e2e test is failing as a result: if not we can go with that change
