### ISSUE TITLE
composer.lock should be appended by default / not excluded

### ISSUE THREAD

**Issue by ostrolucky** [humbug/php-scoper#388]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 0.13.1
| PHP version | 7.4.3
| Platform with version | e.g. Ubuntu/Windows/MacOS
| Github Repo | MacOS

php-scoper generates scoper.inc.php by default that excludes composer.lock. This causes next step that should be run according README file (`composer dump-autoload --working-dir build --classmap-authoritative`) to fail:

```
composer dump-autoload --working-dir build --classmap-authoritative
Generating optimized autoload files (authoritative)


  [LogicException]
  No lockfile found. Unable to read locked packages


dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]
```

**Comment by theofidry** [comment]
I'm not sure to understand: where does it exclude it? https://github.com/humbug/php-scoper/blob/master/src/scoper.inc.php.tpl excludes a few things, including `vendor-bin`, but not `vendor`

**Comment by ostrolucky** [comment]
Hmm probably user error then, it worked after regenerating config
