### ISSUE TITLE
[Scoper] Case sensitiveness handling

### ISSUE THREAD

**Issue by ciaranmcnulty** [humbug/php-scoper#393]
## Bug report

| Question    | Answer
| ------------| ---------------
| Scoper version |  0.13.2
| PHP version | 7.4.0 
| Platform with version | MacOS Catalina

Classes in PHP are case-insensitive, but the scoping rules seem to be case sensitive when using a builtin class.

For instance, `\stdClass` symbols are not prefixed, but a mis-cased `\StdClass` is. This causes obvious issues

I didn't check other builtin types yet

**Comment by theofidry** [comment]
From a few other issues: in general PHP-Scoper treats everything as case sensitive at the moment. It is not clear if it's easily fixable but this should be investigated and if not be marked as a clear limitation in the doc

**Comment by theofidry** [comment]
At least since 0.16 this should be handled
