### ISSUE TITLE
@package annotation should not be preceeded by a newline, but should have one after

### ISSUE THREAD

**Issue by dugajean** [humbug/php-scoper#396]
Generated code looks like this:

```
<?php

/**
 * Blablablab
 *
 * @package MyPkg
 */
namespace My\Namespace;
```

but it should like this in order to comply with phpcs:

```
<?php
/**
 * Blablablab
 *
 * @package MyPkg
 */

namespace My\Namespace;
```

**Comment by dugajean** [comment]
Fixed this with `patchers`.

**Comment by theofidry** [comment]
It's also worth mentioning that there is no CS configuration from PHP_Scoper, it all comes from https://github.com/nikic/PHP-Parser
