### ISSUE TITLE
Add --fix-strings and --fix-global-strings options

### ISSUE THREAD

**Issue by webmozart** [humbug/php-scoper#4]
The options `--fix-strings` and `--fix-global-strings` (suggestions for better names welcome) should be added which do the following:

In a first pass, all class names in the project are collected. Class names that already contain the prefix should be collected as well, but without the prefix (see #6). Then:
- `--fix-strings` adds the namespace prefix to strings that contain non-global class names, e.g. `'Composer\Autoload\ClassLoader'`. This operation should be pretty safe to do.
- `--fix-global-strings` adds the namespace prefix to all strings that contain global class names, e.g. `'ComposerAutoloaderInitFilesAutoloadOrder'`. This operation is risky since strings could look like class names even though they are none (e.g. `'Profile'`), so this needs manual review. The option will typically be used combined with `--diff` to create a patch that can be reviewed and adjusted before being applied.

**Comment by theofidry** [comment]
Fixing the strings will be done by #74 and #10
