### ISSUE TITLE
scoper-autoload.php using class_exists for scoped interfaces

### ISSUE THREAD

**Issue by jarrodbell** [humbug/php-scoper#403]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 0.13.3
| PHP version | 7.2.29
| Platform with version | MacOS

scoped output of `vendor/symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php`

```php
<?php

namespace MyNamespace;

interface SessionUpdateTimestampHandlerInterface
{
    /**
     * Checks if a session identifier already exists or not.
     *
     * @param string $key
     *
     * @return bool
     */
    public function validateId($key);
    /**
     * Updates the timestamp of a session when its data didn't change.
     *
     * @param string $key
     * @param string $val
     *
     * @return bool
     */
    public function updateTimestamp($key, $val);
}
\class_alias('MyNamespace\\SessionUpdateTimestampHandlerInterface', 'SessionUpdateTimestampHandlerInterface', \false);
```

`scoper-autoload.php` contains the following snippet:
```php
if (!class_exists('SessionUpdateTimestampHandlerInterface', false)) {
    class_exists('MyNamespace\SessionUpdateTimestampHandlerInterface');
}
```
The above results in an error:
```
Cannot declare interface SessionUpdateTimestampHandlerInterface, because the name is already in use

vendor/symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php:25
class_alias()
vendor/symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php:25
Composer\A\includeFile()
vendor/composer/ClassLoader.php:322
Composer\A\ClassLoader->loadClass()
Unknown location
spl_autoload_call()
Unknown location
class_exists('MyNamespace\SessionUpdateTimestampHandlerInterface')
vendor/scoper-autoload.php:25
```

If I change the `scoper-autoload.php` snippet above to the following instead, the error is gone:
```php
if (!interface_exists('SessionUpdateTimestampHandlerInterface', false)) {
    interface_exists('MyNamespace\SessionUpdateTimestampHandlerInterface');
}
```

Is there something I am missing to make sure `scoper-autoload.php` correctly uses `interface_exists` for Interfaces?

**Comment by discordier** [comment]
Problem got introduced in #340.

I'd love to solve this, however, we do not know what the passed class-string is.

Therefore the only possible solution that pops into my mind is by swapping the guard with this:
```php
return sprintf(
    <<<'PHP'
if (!class_exists('%1$s', false) && !interface_exists('%1$s', false) && !trait_exists('%1$s', false)) {
    spl_autoload_call('%2$s');
}
PHP
    ,
    $originalClass,
    $prefixedClass
);
```

**Comment by theofidry** [comment]
Ugh that makes me wonder how the trait whitelisting is supported right now (I don't think it is).

Otherwise I think your solution is pretty good: it's a lot easier than registering the type to the whitelist too (which would be nice but is a non negligible amount of work) 👍

**Comment by discordier** [comment]
> Ugh that makes me wonder how the trait whitelisting is supported right now (I don't think it is).

I sadly lack a trait from global namespace, so I really can't tell. We'll to test that one separately I guess, however I think it won't hurt supporting it already here and leave it to the other implementation parts of the scoper to catch up later.

> Otherwise I think your solution is pretty good: it's a lot easier than registering the type to the whitelist too (which would be nice but is a non negligible amount of work)

This is why I refrained from transporting multiple lists of classes, interfaces and traits (and maybe in future who knows what else might appear).

To put long story short, my throw at it is in #417
