### ISSUE TITLE
[Scoper] Add support for inclusive namespace whitelisting

### ISSUE THREAD

**Issue by Konamiman** [humbug/php-scoper#406]
## Feature Request

Right now the `whitelist` section in the configuration file is _exclusive_: all the classes will be scoped except those whose namespace is in the whitelist.

It would be nice to have an option for the whitelist to be _inclusive_ instead, so that it works the reverse way: only the classes whose namespace is in the whitelist will be scoped, all others will be untouched.

I think the easier way to implement this would be to add a new boolean configuration option like `namespace_whitelist_is_inclusive`, defaulting to `false` for compatibility with the current behavior.

This is something I actually need for my job so I can implement it and submit a pull request. In fact I've already been experimenting with the code and seems definitely doable.

**Comment by theofidry** [comment]
👍 maybe `inverse_whitelist` would be more fitting than `namespace_whitelist_is_inclusive`?

**Comment by Konamiman** [comment]
The tool supports different kinds of whitelists (namespaces, constants, functions...) so I think the keyword should explicitly reference namespaces for clarity.

Also "inclusive" is perhaps more explicit than "inverse" but either would be fine imho.

**Comment by theofidry** [comment]
This can now be achieved. Excluding/exposing a namespace is recursive but if you wish a different behaviour the namespace can be excluded/exposed via a regex instead which should give you all the freedom needed
