### ISSUE TITLE
Shared dependencies are "duplicated"?

### ISSUE THREAD

**Issue by alessandrotesoro** [humbug/php-scoper#415]
Hi there,

I'm developing a micro framework (for WordPress plugins) which is made out of different composer packages that in some cases share the same dependencies. I've noticed that when running php-scoper the shared dependencies are duplicated underneath each package that has the dependency.

Example:
I have a package named `tld/my-feature` that requires `tld/utilities`.
I have another package named `tld/my-other-feature` that requires `tld/utilities`.

I then have the "main application" that requires `tld/my-feature` and `tld/my-other-feature`. When using php-scoper I then have a folder with all the dependencies prefixed but the `tld/utilities` package has been duplicated. Once for `tld/my-feature` and once for `tld/my-other-feature`.

Is this the expected behavior? Is there any way to avoid this from happening? 

PS: I tried to find your slack as it says on github before opening the issue but couldn't find any mention or link to Slack.

Thank you :)

**Comment by theofidry** [comment]
Hi,

Indeed that's the expected behaviour. Once scoped, you cannot deduplicate/share it anymore. And I admit I have no clue on how that could be fixed

**Comment by alessandrotesoro** [comment]
Hey @theofidry thanks for your reply. I guess I'll restructure my framework.
