### ISSUE TITLE
How to use this to prefix a WordPress plugin?

### ISSUE THREAD

**Issue by Luc45** [humbug/php-scoper#442]
Howdy!

I tried to use PHP-Scoper to prefix a WordPress plugin but couldn't. I saw the issue https://github.com/humbug/php-scoper/issues/303 and the PR https://github.com/humbug/php-scoper/pull/433, I've read through a fair amount of comments and tried to get hands down with it myself.

I will list the steps I took to scope my WordPress plugin `vendor` folder, and the results that I've got:

### Approach 1, per-dependency scope:

File: [scoper-di52.php](https://pastebin.com/0Ary9esZ)

```
php /var/www/tests/php-scoper/php-scoper.phar add-prefix --output-dir=/var/www/single/wp-content/plugins/wp-staging-dev/vendor_prefixed/lucatume/di52 --config=/var/www/tests/php-scoper/scoper-di52.php
```

Result: The prefixed di52 package in `vendor_prefixed/lucatume/di52`, as is expected. But there are a few issues with this approach:

- The prefixed library is outside the Composer Autoloader, which means I would have to autoload it in a different way?
- The original, unprefixed library, is still being loaded on the Composer Autoloader

### Approach 2, scope the entire `vendor` folder: 

File: [scoper.php](https://pastebin.com/712YvaZn)

```
php /var/www/tests/php-scoper/php-scoper.phar add-prefix --output-dir=/var/www/single/wp-content/plugins/wp-staging-dev/vendor_prefixed --config=/var/www/tests/php-scoper/scoper.php
```

Result: All `vendor` dependencies prefixed in the `vendor_prefixed` folder, including Composer itself. This should work, but I had to add this to the `scoper.php` file, which raises an eyebrown for other exceptions that I might be missing and find out it can cause a fatal down the road:

```php
'patchers' => [
    function (string $filePath, string $prefix, string $contents): string {
        // Change the contents here.

        if ($filePath === '/var/www/single/wp-content/plugins/wp-staging-dev/vendor/composer/autoload_real.php') {
            $contents = str_replace('\'Composer\\\\Autoload\\\\ClassLoader\'', '\'MyPlugin\\\\Vendor\\\\Composer\\\\Autoload\\\\ClassLoader\'', $contents);
            $contents = str_replace('\'Composer\\Autoload\\ClassLoader\'', '\'MyPlugin\\Vendor\\Composer\\Autoload\\ClassLoader\'', $contents);
        }

        return $contents;
    },
],
```

Patching is somewhat expected, but the fact that I had to do it in Composer Autoloader worries me, as the autoloader seems fragile as it's auto-generated.

With approach 1, I have added this to my composer.json so it can find the prefixed classes:

```
"autoload": {
  "psr-4": {
    "MyPlugin\\": "",
    "MyPlugin\\Vendor\\": "vendor_prefixed"
  }
}
```

I'm not sure if this would work well for attempt 2.

Am I taking the right approach to scope this WordPress plugin? Is there a third approach I should consider?

Thanks!

**Comment by Luc45** [comment]
I see that Yoast and Google Site Kit uses PHP Scoper to prefix their WordPress plugins.

Both implementations seem to go through a fair amount of effort to implement their own autoloading solutions for the prefixed vendor classes.

1. Yoast prefixes the vendor classes
2. Removes them from Composer Autoloader
3. [Implement](https://github.com/Yoast/wordpress-seo/blob/11.3/src/config/dependency-management.php#L23-L48) a `spl_autoload_register`, scan the requested namespace, and if it begins with the prefix, alias it to an "unprefixed" one. _(I wonder if it defeats the purpose of Scoping it at the first place?)_

1. Google Site Kit takes a similar approach, [implementing](https://github.com/google/site-kit-wp/pull/730/files#diff-067193c915671062a08eb302c679c0beddb7154eb4d3c7db7feda18d78da4c4cR23-R43) their own `spl_autoload_register` autoloader, and it seems it drops Composer autoloader entirely.

WooCommerce is [taking](https://github.com/woocommerce/woocommerce/pull/28147) the [Mozart](https://github.com/coenjacobs/mozart) route.

Can PHP Scoper work with Composer autoloader? Would you recommend using PHP Scoper on a WordPress plugin?

**Comment by Luc45** [comment]
I ended up figuring it out.

This approach is similar to Google Site Kit, generating a class map to avoid Composer doing `file_exists` checks on the filesystem.

The scoping process should happen as part of a build process of a distributable version of the plugin. not for development. Understand why [here](https://getcomposer.org/doc/articles/autoloader-optimization.md). _(This approach uses the Optimization Level 1: Class map generation)_

This is not mean to be a copy-and-work solution. In this example I use Docker to have predictable paths, you might need to adjust those to your reality. I also use the Phar version of PHP-Scoper.

Makefile:
```
.PHONY: php-scoper

php-scoper:
	# Cleanup
	rm -rf vendor_prefixed

	# Install Dependencies
	composer install --no-dev --prefer-dist --no-scripts

	# Prepare prefixed vendor
	mkdir vendor_prefixed
	cp composer.json vendor_prefixed/composer.json
	cp composer.lock vendor_prefixed/composer.lock

	# Add Prefix
	docker exec --user www-data -i wpstaging_php bash -c "php /var/www/tests/php-scoper/php-scoper.phar add-prefix --output-dir=/var/www/single/wp-content/plugins/wp-staging-dev/vendor_prefixed/vendor --config=/var/www/tests/php-scoper/scoper.php --force"

	# Generate prefixed vendor classmap
	composer dump-autoload --working-dir=vendor_prefixed --optimize --no-scripts

	# Remove prefixed dependencies from vendor
	cp composer.lock composer.lock.bk

	composer remove --no-scripts \
	    lucatume/di52\
	    symfony/finder\
	    symfony/filesystem\
	    psr/log

	composer install --no-dev --prefer-dist -o --no-scripts

	rm -f composer.lock

	mv composer.lock.bk composer.lock

```

composer.json:
```
"scripts": {
    "post-autoload-dump": "make php-scoper"
}
```

Loading the autoloader in the plugin (Inspired by Google Site Kit):
```php
$class_map = array_merge(
    require_once __DIR__ . '/vendor/composer/autoload_classmap.php',
    require_once __DIR__ . '/vendor_prefixed/vendor/composer/autoload_classmap.php'
);

spl_autoload_register(
    function ($class) use ($class_map) {
        if (isset($class_map[$class])) {
            require_once $class_map[$class];

            return true;
        }

        return null;
    },
    true,
    true
);
```
`'/vendor/composer/autoload_classmap.php'` contains a classmap for the `src` code
`'/vendor_prefixed/vendor/composer/autoload_classmap.php'` contains a classmap for the `vendor_prefixed` code

Check the contents of those two files to see if everything looks right to you.

**Comment by Luc45** [comment]
Re-opening this as privately _requested_ for visibility and further discussion around the subject.

Maintainers of this package, please feel free to close this if you see fit.

**Comment by theofidry** [comment]
@Luc45 thanks for opening the issue; there is also #303. There is some ideas I hope to get to it in the coming weeks; It's a good idea to keep this issue as well to come back to it after I think

**Comment by swissspidy** [comment]
Since you mentioned Site Kit by Google, you might also want to check out how we've done the prefixing in another Google plugin here: https://github.com/google/web-stories-wp/.

**Comment by leoloso** [comment]
I just published how I scoped my WordPress plugin: https://graphql-api.com/blog/graphql-api-for-wp-is-now-scoped-thanks-to-php-scoper/

**Comment by theofidry** [comment]
There is plenty of answers here so I'll be closing this issue. I am not satisfied with the WP support but I'll keep #303 for this purpose.
