### ISSUE TITLE
Handle Composer autoloading

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#46]
Follow up of https://github.com/humbug/php-scoper/pull/38#issuecomment-307658139

**Comment by theofidry** [comment]
#52 is not enough as it covers the case where Composer handle only the root package. It seems however that for the dependencies, it fetches the package metadata from elsewhere

**Comment by padraic** [comment]
https://github.com/composer/composer/blob/a3f2b7bb92a54f4e25b2d0998f00936ecac6f933/src/Composer/Installer.php#L262

Looks like the lock file and autoloader aren't linked. I've lost my familiarity with the composer code, but this suggests both are using the package metadata as mutually exclusive operations.

**Comment by theofidry** [comment]
Yep looks like this is the wrong approach. Most likely Composer gets the data from Packagist directly and cache it somewhere, I could find a `~/.composer/cache/repo/https---packagist.org/provider-beberlei\$assert.json` file for example. Makes me wonder if we should try too hook on Composer to fix that or rather fix the dumped files directly

**Comment by padraic** [comment]
We could try hooking, but whether that's simpler (or alternatively less error prone) than string manipulating the dumped file, I don't know.
