### ISSUE TITLE
Unicode Entities

### ISSUE THREAD

**Issue by matzeeable** [humbug/php-scoper#464]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.14.0
| PHP version | 7.4.15 
| Platform with version | Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
| Github Repo | https://github.com/maxmind/MaxMind-DB-Reader-php 

## Steps to reprocedure

```sh
composer require maxmind-db/reader:~1.0`
cd vendor/maxmind-db/reader/src/MaxMind/Db
php-scoper add-prefix Reader.php
```

## Input

https://github.com/maxmind/MaxMind-DB-Reader-php/blob/d11b3a70fd7019986129f09b24d545e18d3ac581/src/MaxMind/Db/Reader.php#L30

```php
    /**
     * @var string
     */
    private static $METADATA_START_MARKER = "\xAB\xCD\xEFMaxMind.com";
```

## Output

```php
    /**
     * @var string
     */
    private static $METADATA_START_MARKER = '���MaxMind.com';
```

I think there is something wrong with the encoding.

Regards,
Matthew 😊

**Comment by theofidry** [comment]
It appears so: https://github.com/humbug/php-scoper/pull/467

**Comment by marekdedic** [comment]
nikic/PHP-Parser#763 is probably the cause.
