### ISSUE TITLE
Sign PHAR

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#47]
I saw a box option regarding the PHAR version as well, not sure how you configure/handle it @padraic.

**Comment by padraic** [comment]
I keep a `box.json.dist`, and replace it locally with a `box.json`. The rest is just setting the signature algo (openssl), and the path to a private key. I never add the key password to the local config (though box allows you to do so). I can't remember the params off hand - I think I actually had to read the code to find the exact config keys back in the day.

The tricky part is that PHAR's have no method for delegated signing (a basic limitation of PHARs), or retiring lost/compromised private keys (no existing implementation in our dependencies). We can't do anything about the first, but the second might be achievable from `phar-updater` using a URL response to signal when a private key has been changed, and notifying the user and asking them if they should continue an update using the new key. Hmm, will add an issue on the phar-updater repo to look into this.

**Comment by theofidry** [comment]
Ok, so that means you'll have to do the release as you need to sign the PHAR then?

**Comment by padraic** [comment]
You can create your own key if you want to handle releases here, and it's better to have distinct keys so any compromise/loss is limited in scope to just one app. My blog is enjoying oblivion right now, but here's some overview: https://mwop.net/blog/2015-12-14-secure-phar-automation.html

That provides the key generation command, and hey, it also has the box params!

**Comment by theofidry** [comment]
Just what I needed :ok

**Comment by padraic** [comment]
Can this issue be closed?

**Comment by theofidry** [comment]
Yeah let's close this, I'll come back to you later if necessary for the releases
