### ISSUE TITLE
Global classes get namespaces prefixed

### ISSUE THREAD

**Issue by L3RAZ** [humbug/php-scoper#471]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.14.0
| PHP version | 7.3.27-9
| Platform with version | Ubuntu 20.04
| Github Repo | -

Hello!
We are having problems with scoping where php-scoper adds namespace prefix for global classes even though config is set to whitelist global classes.

Here's an example, used with config file below:

```php
<?php

namespace ModuleScoped;

require_once __DIR__ . '/vendor/autoload.php';
if (!\defined('_PS_VERSION_')) {
    exit;
}
class Module extends \ModuleScoped\PaymentModule
{
...
```
In this case \PaymentModule is a global class that must not be scoped and event if I add it to config it gets scoped anyways. How can this be resolved? Also this example class was added to whitelist, but still got a namespace added when it should be left global.
<details>
 <summary>scoper.inc.php</summary>
 
 ```php
<?php

declare(strict_types=1);

use Isolated\Symfony\Component\Finder\Finder;

return [
    // The prefix configuration. If a non null value will be used, a random prefix will be generated.
    'prefix' => 'ModuleScoped',

    'finders' => [
        Finder::create()
            ->files()
            ->ignoreVCS(true)
            ->notName('/LICENSE|.*\\.md|.*\\.dist|Makefile|composer\\.json|composer\\.lock/')
            ->exclude([
                'docs',
                'test',
                'test_old',
                'tests',
                'Tests',
                'vendor-bin',
                '_dev',
                'translations',
                'upgrade',
            ])
            ->in('ps_checkout'),
//        Finder::create()->append([
//            'composer.json',
//        ]),
    ],

    'files-whitelist' => [
        'src/a-whitelisted-file.php',
    ],

    'patchers' => [
        function (string $filePath, string $prefix, string $contents): string {
            // Change the contents here.

            return $contents;
        },
    ],

    'whitelist' => [
        '\PaymentModule',
        'PaymentModule',
        'Module',
    ],


    'whitelist-global-constants' => true,

    'whitelist-global-classes' => true,
`
    'whitelist-global-functions' => true,
];


 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ command
 > output
 ```
</details>

**Comment by theofidry** [comment]
Hi, indeed this is expected see https://github.com/humbug/php-scoper#implementation-insights. The whitelisting is done via aliasing (hence the need to load the scoper-autoload.php file) to avoid breaking Composer autoloading
