### ISSUE TITLE
global "Stingable" polyfill does not receive a class_alias

### ISSUE THREAD

**Issue by veewee** [humbug/php-scoper#473]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.15.0
| PHP version | 8.0.1
| Platform with version | MacOS
| Github Repo | https://github.com/phpro/grumphp-shim/pull/12

Our project includes the PHP80 polyfill of symfony:

https://github.com/symfony/polyfill-php80/blob/dc3063ba22c2a1fd2f45ed856374d79114998f91/Resources/stubs/Stringable.php#L1-L11

After scoping, it looks like this:

```php
<?php
namespace _HumbugBox5ecae77e191c;

if (\PHP_VERSION_ID < 80000) {
    interface Stringable
    {
        /**
         * @return string
         */
        public function __toString();
    }
}
```

As you can see, the class_alias is missing, making the phar fail on php 73 and php 74:
https://github.com/phpro/grumphp-shim/runs/2568827516?check_suite_focus=true

```
PHP Fatal error:  Interface 'Stringable' not found in phar:///home/runner/work/grumphp-shim/grumphp-shim/grumphp.phar/vendor/symfony/string/AbstractString.php on line 28
```

For now I added a workaround patcher (see below), that makes the file look like this:

```php
<?php

namespace _HumbugBox5ecae77e191c;

if (\PHP_VERSION_ID < 80000) {
    interface Stringable
    {
        /**
         * @return string
         */
        public function __toString();
    }
}
if (\PHP_VERSION_ID < 80000) {
    \class_alias('_HumbugBox5ecae77e191c\\Stringable', 'Stringable', \false);
}

```

After this change, it works as expected.
https://github.com/phpro/grumphp-shim/pull/12/checks?check_run_id=2568871719

At this moment, I guess that scoper is not able to put a class alias near an interface that is defined inside an if statement.

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
 <?php
 
 declare(strict_types=1);

 
return [
    'whitelist-global-classes' => true,
    'patchers' => [
        // This fixes the bug for now ...
        // But isn't optimal ...
        static function (string $filePath, string $prefix, string $contents): string {
            if ($filePath !== 'vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php') {
                return $contents;
            }

            $contents .= 'if (\PHP_VERSION_ID < 80000) {'.PHP_EOL;
            $contents .= "    \class_alias('$prefix\\\\Stringable', 'Stringable', \\false);".PHP_EOL;
            $contents .= "}".PHP_EOL;

            return $contents;
        }
    ]
];


 ```
</details>

**Comment by theofidry** [comment]
See https://github.com/humbug/php-scoper/pull/481 for an example on how to fix it

**Comment by veewee** [comment]
Thanks, will try it out soon

**Comment by veewee** [comment]
This works like a charm. Thanks!

FYI: it does conflict with the composer autoload files regex fixes provided in https://github.com/humbug/php-scoper/issues/298.
Changing the regex does the trick:

```php
        $static_loader = \preg_replace(
            '/\'([a-z0-9]*?)\' => __DIR__ \. (.*?),/',
            '\'scoped$1\' => __DIR__ . $2,',
            $static_loader
        );
```

(The hashes are always lower-cased, and the symfony stub classes start with a capital.)
