### ISSUE TITLE
Scope files in the global namespace

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#53]
I had a simple file:

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

echo (new \Foo\Foo())().PHP_EOL;
```

Where `Foo` was an invokable. Surprisingly the scoping did not prefix `\Foo\Foo()` to `PhpScoperPrefix\Foo\Foo()`.

**Comment by padraic** [comment]
I don't think we specifically test that case either. The only related test would be for the single level variant, e.g. `new \ArrayObject()`.

**Comment by theofidry** [comment]
Hm not sure to follow, wasn't https://github.com/humbug/php-scoper/pull/14 about that: listing what is to skip e.g. `stdClass` so that we can prefix such things?

**Comment by padraic** [comment]
https://github.com/humbug/php-scoper/blob/master/src/NodeVisitor/IgnoreNamespaceScoperNodeVisitor.php#L31

My fault, I think. Pretty sure, this line should be `&& 1 === count($node->parts)`. I can't test it right now, but on a FQN, the original line would currently be TRUE all the time. That, and we need tests for this so it doesn't happen again.

**Comment by theofidry** [comment]
Meh that's fine, I expect a lot of those kind of errors in the future, we just need to make more tests as we encounter them :P

**Comment by theofidry** [comment]
I think we need something like https://github.com/humbug/php-scoper/pull/28/commits/eda92216ea51c88fe9c41659bcb9d039f0a29041#diff-c886d72814bef4bd6c11e9ca596caa85R16 to avoid those cases.

Alternatively we can also just leave it a that and recommend to use `use` statements...
