### ISSUE TITLE
Composer install for contribution fails on conflitcs

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#534]
Hi Theo,

I'm trying to contribute via fresh fork (https://github.com/TomasVotruba/php-scoper), but I fail to get bar composer install. 

I've tried various hackings like:

* change `"replace"` in `composer.json` to specific version
* use PHP 8, use PHP 7.4
* remove `composer.lock`
* run `composer install`
* run `composer update`
* run `composer install --no-interaction --no-progress --no-suggest --prefer-dist --ansi`

But nothing works for me.

<br>

## Steps to Reproduce

```
git clone https://github.com/TomasVotruba/php-scoper.git
cd php-scoper
composer install
```

<br>

```bash
  Problem 1
    - humbug/box is locked to version dev-master and an update of this package was not requested.
    - humbug/box dev-master requires humbug/php-scoper ^0.13.10 || ^0.14 -> found humbug/php-scoper[dev-master, 1.0.x-dev (alias of dev-master)] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
  Problem 2
    - humbug/box dev-master requires humbug/php-scoper ^0.13.10 || ^0.14 -> found humbug/php-scoper[dev-master, 1.0.x-dev (alias of dev-master)] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
    - humbug/box 3.x-dev is an alias of humbug/box dev-master and thus requires it to be installed too.
    - humbug/box is locked to version 3.x-dev and an update of this package was not requested.
```

Any ideas what I'm doing wrong?

**Comment by TomasVotruba** [comment]
This is failing GitHub Action with the exact output: https://github.com/humbug/php-scoper/pull/535/checks?check_run_id=3290677049

![image](https://user-images.githubusercontent.com/924196/128865308-d4b612f7-4f87-486c-b9dd-8c9eca71cbc1.png)

(screenshot in case the GitHub Action result is deleted)

**Comment by theofidry** [comment]
Hi,

Yes you need to do `source .composer-root-version` or alternatively set the `COMPOSER_ROOT_VERSION` env variable manually.

It might be worth adding to the contributing doc, but the regular install commands and others should be done via the Makefile which IIRC should already take care of that issue

**Comment by TomasVotruba** [comment]
Thanks for answer. Can we make this somehow part of `composer.json` itself? I had similar bug with Simplify, but managed to remove it.

**Comment by TomasVotruba** [comment]
> It might be worth adding to the contributing doc

That would save me couple of hours :laughing: :+1: I looked there but could not find anything

**Comment by theofidry** [comment]
>Thanks for answer. Can we make this somehow part of composer.json itself? I had similar bug with Simplify (Rector uses Simplify stable, but Symplify is in dev-main), but managed to remove it.

I did not find a way to.

>That would save me couple of hours 😆 👍 I looked there but could not find anything

I think it was added much later which may be why it was missing, but it does mention the Makefile :P
