### ISSUE TITLE
Outdated stubs lead to error

### ISSUE THREAD

**Issue by sebastianbergmann** [humbug/php-scoper#540]
From a [PHPUnit job](https://github.com/sebastianbergmann/phpunit/runs/4089590449?check_suite_focus=true):

```
[phpunit] An error occurred inside PHPUnit.
  [phpunit] 
  [phpunit] Message:  Call to undefined function PHPUnit\xdebug_info()
  [phpunit] Location: phar:///home/runner/work/phpunit/phpunit/build/artifacts/phpunit-snapshot.phar/php-code-coverage/Driver/XdebugDriver.php:97
```

The `xdebug_info()` function is provided by Xdebug since version 3.1.0. Looks to me like the version of `jetbrains/phpstorm-stubs` bundled in the PHP-Scoper PHAR does not know `xdebug_info()` yet which is why PHP-Scoper rewrites `xdebug_info()` to `PHPUnit\xdebug_info()` which does not exist.

**Comment by sebastianbergmann** [comment]
@theofidry In the meantime, is there anything I can do in [PHP-Scoper's configuration](https://github.com/sebastianbergmann/phpunit/blob/master/build/config/php-scoper.php) to prevent `xdebug_info()` from getting rewritten? Thanks!

**Comment by sebastianbergmann** [comment]
I tried to use `exclude-functions` documented in https://github.com/humbug/php-scoper#excluded-symbols:
```patch
--- a/build/config/php-scoper.php
+++ b/build/config/php-scoper.php
@@ -12,4 +12,7 @@
     'whitelist' => [
         'PHPUnit\*',
     ],
+    'exclude-functions' => [
+        'xdebug_info'
+    ],
 ];
```
However, this results in an error:
```
In Configuration.php line 137:

  Invalid configuration key value "exclude-functions" found.
```

**Comment by theofidry** [comment]
@sebastianbergmann I'll check that during the week

**Comment by theofidry** [comment]
ha before that: it may be that the doc points to the latest commit which is different than the latest release, hence a diff

**Comment by sebastianbergmann** [comment]
Sorry for the confusion: I posted a diff because I wanted to highlight the lines that I added to the [php-scoper.php](https://github.com/sebastianbergmann/phpunit/blob/master/build/config/php-scoper.php) configuration file that I use for PHPUnit.

Here is the complete file that I tried with PHP-Scoper 0.15.0:

```php
<?php declare(strict_types=1);
/*
 * This file is part of PHPUnit.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    'whitelist' => [
        'PHPUnit\*',
    ],
    'exclude-functions' => [
        'xdebug_info'
    ],
];
```
