### ISSUE TITLE
Handle custom string manipulations

### ISSUE THREAD

**Issue by padraic** [humbug/php-scoper#63]
@theofidry I checked briefly into the PHAR problems, and it seems to boil down to PHP Parser referring to specific classes and functions using strings (which we aren't scoping). Two examples:

`PhpParser\Lexer::createTokenMap()`:
```php
if (defined($name = 'PhpParser\\Parser\\Tokens::' . $name)) {
    // Other tokens can be mapped directly
    $tokenMap[$i] = constant($name);
}
```
Straightforward class name in a string which is not scoped. This is the first problem encountered. When fixed, you find another when Pretty Printing. I assume at that point we've gone through most of the parsing, so there may just be a couple of these.

`PhpParser\PrettyPrinterAbstract::p()`:
```php
/**
 * Pretty prints a node.
 *
 * @param Node $node Node to be pretty printed
 *
 * @return string Pretty printed node
 */
protected function p(Node $node)
{
    return $this->{'p' . $node->getType()}($node);
}
```
The `$node->getType()` returns the class ref which is prefixed, so the function name is corrupted and causes a fatal error.

The outcome of the problem is that scoped files are empty apart from an opening PHP tag. So essentially, we need a facility to apply simple patches to files. I'm not sure if they should target before or after scoping. I suspect doing it beforehand is simpler, but debugging takes place after (and pretty printing meddles with line numbers in between). Might be useful to have a shortcut to extract the phar from php-scoper itself for ease of debugging. I'm using the following the extract the phar at the moment:

`php -r '$phar = new Phar("bin/php-scoper.phar"); $phar->extractTo("./build/extract");'`

**Comment by theofidry** [comment]
I think we would be better off trying to patch PhpParser rather

**Comment by padraic** [comment]
Just for reference, the second example can be resolved with (23 being uniqid() string length):

`PhpParser\NodeAbstract::getType()`:
```php
public function getType()
{
    return strtr(substr(rtrim(get_class($this), '_'), 15+23), '\\', '_');
}
```
No further errors thereafter.

As regards patching, we can patch this directly (if that's what you mean, via makefile), but the prefix is not static so we still need a way to advise the patching op of what the prefix is, so patching needs to be done either during scoping (which the issue title suggests) or post-scoping when we can signal or retrieve it - perhaps even just dump the prefix to a simple file for reading instead of searching for it.

**Comment by theofidry** [comment]
I meant to do a PR on PhpParser to update the code to be more PHPScoper friendly instead. If it doesn't add complexity and works well, I don't see why it wouldn't be accepted.

>So essentially, we need a facility to apply simple patches to files

Eventually we'll be forced to apply this kind of patch, but I would prefer to try to delay this as much as possible.

Two possible solutions though:

- Via the Node traverser (the simplest solution I think but the performance impact might be non-negligeable
- Analyse the file content and change it with a `preg_replace()` or something

**Comment by padraic** [comment]
I'm more worried about other users being forced to, so I'm not sure it needs to be delayed. At a minimum, we can easily document the problem and solutions with other tools, e.g. `patch`.

I would go with keeping it relatively simple for downstream users - an array of filenames, search strings and replacement strings, a decorated scoper to apply them, and an input option to import them from a file format. Then mention the existence of options that can alternatively be used post-scoping in the README.

**Comment by theofidry** [comment]
Yeah we'll definitely need an extension point for that
