### ISSUE TITLE
PHAR versioning

### ISSUE THREAD

**Issue by padraic** [humbug/php-scoper#64]
AFAIK, the package for setting the version string ignores local release tags, so this will set the version for all phars to the commit hash. As we need a valid version string for updating down the line, an alternative mode when building phars (or using the phar) is needed.

**Comment by theofidry** [comment]
Maybe we can find a hook for that to rely on the commit version, keeping things in sync is always a PITA

**Comment by padraic** [comment]
We'll need to add back a replaceable tag either way to inject the version string. Simplest is probably falling back on git and sed from the makefile, but Box should be able to do that automatically if we disable the "ignore VCS" option in our Finder instance (which is probably more user friendly and preferable in the end).

**Comment by theofidry** [comment]
Is this still relevant?

**Comment by padraic** [comment]
Not any longer...though I'm now curious as to why not. It really should be broken!

Here's what I think is happening. We scoping all files to `build`, but running `box` from current directory. So we're using the original `box.json` configuration (not `build/box.json`). Git commands are run from the location of the file used, not from within `build`.

So long as we assume nobody tries running box from inside `build`, nothing to do here. Of course, that's exactly what I originally tried before you wrote the makefile ;). We may need a `--copy-vcs` option or similar down the line - I'm not sure I want to assume how users will do things.

**Comment by theofidry** [comment]
Actually another thing is that we rely on OcramiusPackageVersion to get the version which gets it from the installed packages not git itself, so we are completely ditching box git version placeholders :)
