### ISSUE TITLE
Add better PHPUnit support

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#640]
See https://gist.github.com/sebastianbergmann/9eba10f9e61c576950df8bcd37712992#file-phar-md.

It would be interesting to have PHPUnit, as we have Infection, part of the e2e test suite.

**Comment by theofidry** [comment]
@sebastianbergmann do you have any tests you run or can run with the scoped PHARs afterwards to ensure it works as expected?

**Comment by sebastianbergmann** [comment]
Sure: `ant run-phar-specific-tests-with-scoped-phar`

**Comment by theofidry** [comment]
Note to myself: do the same with:

- PHPStan
- Infection (e2e_020)
