### ISSUE TITLE
PHP Scoper can't handle nested namespace

### ISSUE THREAD

**Issue by alexander-schranz** [humbug/php-scoper#650]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.16.0 
| PHP version | 8.0.15 
| Platform with version | MacOS
| Github Repo | - 

The PHP Scoper seems not to work well when the namespace is nested like in twig core extension:

```php
namespace {

}
```

https://github.com/twigphp/Twig/blob/237f1789a7db3a0cbb8e28a75832a45b7f9fc304/src/Extension/CoreExtension.php#L305-L314

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
<?php declare(strict_types=1);

// scoper.inc.php

return [
    'exclude-namespaces' => [ 'Twig' ],
];
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ box compile
 > works
 ```
 
 But the Twig Core Extension looks like this:
 
 ```php
namespace Twig\Extension;

// ..

class CoreExtension {
   // ..
}

// now the strange part coming:
 
namespace _PhpScoper8f79d0649963;

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\CoreExtension;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Source;
use Twig\Template;
use Twig\TemplateWrapper;

// ..
 ```
 
See also: 
https://github.com/twigphp/Twig/blob/237f1789a7db3a0cbb8e28a75832a45b7f9fc304/src/Extension/CoreExtension.php#L305-L314

When running the phar I'm getting:

> Fatal error: Uncaught Error: Call to undefined function twig_split_filter()
</details>

**Comment by alexander-schranz** [comment]
Found a workaround by exluding `/^$/` namespace from scoping. Twig itself need also be excluded but think php scoper can not do there much:


```php
<?php declare(strict_types=1);

// scoper.inc.php

return [
    'exclude-namespaces' => [
        'Twig', // twig does not like to be scoped
        '/^$/', // fix problem with twig global namespace: https://github.com/humbug/php-scoper/issues/650
    ],
];
````

**Comment by alexander-schranz** [comment]
> twig registers functions in the global scope

Agree I think that is was what the following code snippet does (never used this myself 🙈):

```php
namespace {
}
```

Strange is that I also got some errors that it could not find `Twig\Template` class. Think twig itself uses some hacks which make it not really possible for the scoper to find alle class or namespace references to scope them. 

Do you have yourself experience with using Twig inside a scoped phar?

> I would by default always suggest exposing over excluding

Sounds interesting will give it a try and check if that maybe works better.

**Comment by theofidry** [comment]
>Do you have yourself experience with using Twig inside a scoped phar?

Unfortunately no. I'm also not sure what it entails exactly as I suspect twig stores some cache somewhere which must be configured to be out of the PHAR.

**Comment by alexander-schranz** [comment]
> Unfortunately no. I'm also not sure what it entails exactly as I suspect twig stores some cache somewhere which must be configured to be out of the PHAR.

The cache is as I know optional. But in my case it is outside the phar currently. Was experementing with putting it into the phar (already compiled) but the hash didn't match think the file path is part of the hash.

> Although not ideal ultimately all of them can be fixed via patchers.

Or maybe get twig into direction being more scoper friendly by not hardcode namespace usages (replace with `__NAMESPACE__`) and avoid using "global" functions :)

But at current state I'm fine with using `'/^$/'`. Thx you for your help here!

**Comment by theofidry** [comment]
Closing this now, do feel free to open a new issue if you encounter another problem :)
