### ISSUE TITLE
Exclude string literal escaping (\) based on prefix

### ISSUE THREAD

**Issue by wakaloka-dev** [humbug/php-scoper#673]
How to exclude string literal escaping (`\`) based on prefix?
I want to exclude all strings starting with `f!`.

Original:
```
add_filter('f!Wakaloka\PlainClasses::get_instance', fn ($service) => $service->instance);
```

Result:
```
add_filter('f!Wakaloka\\PlainClasses::get_instance', fn ($service) => $service->instance);
```

Expected:
```
add_filter('f!Wakaloka\PlainClasses::get_instance', fn ($service) => $service->instance);
```

**Comment by wakaloka-dev** [comment]
I have read this docs section [#String values](https://github.com/humbug/php-scoper/blob/master/docs/limitations.md#string-values).

Is it absolutely impossible?

**Comment by theofidry** [comment]
@wakaloka-dev sorry for the late answer. It is not possible for PHP-Scoper itself, but still possible for you by leveraging patchers where you have complete control.
