### ISSUE TITLE
Original "whitelist" functionality instead of "expose-namespaces"

### ISSUE THREAD

**Issue by ondrejmirtes** [humbug/php-scoper#677]
Hello,
I just upgrade to Box 4.0.0 and it looks like it comes with a newer version of PHP-Scoper that doesn't have some original configuration options.

I figured out that `files-whitelist` has been replaced by `exclude-files` which probably works the same way, but `whitelist` (that accepts namespace patterns) has been replaced with `expose-namespaces` that works differently.

Originally, `whitelist` simply didn't prefix listed namespaces which was ideal for me. But `expose-namespaces` prefixes all namespaces and generates `class_alias` calls in `vendor/autoload.php`.

Would it be possible to somehow restore the original `whitelist` behaviour?

I noticed only because PHP-Scoper generates invalid code (https://gist.github.com/ondrejmirtes/81e4a2c63f011edea470d8b411efa176) but that's not the subject of my question. I'd like to match the original behaviour as much as possible because that's how prefixed and compiled PHPStan looked like for several years now, and I'd like to preserve that, because it's well-tested, and I'm afraid of unintended consequences.

**Comment by theofidry** [comment]
@ondrejmirtes sorry for the very late reply. I think the right setting for it is `exclude-namespaces` instead of `expose`. I am pretty certain the equivalent of `whitelist` could be achieved since I only adapted the specification tests, not completely rewrote them.

**Comment by ondrejmirtes** [comment]
@theofidry Looks like it's better, but there's a bug. When I set (https://github.com/phpstan/phpstan-src/pull/1481/commits/b0a8956563590ffdbe1c4d564cbf78d542b5ac57) `exclude-namespaces` with the `PhpParser`, and there's `use PhpParser;` somewhere, it gets changed to `use _PHPStan_a2fab0338\PhpParser;`.

If you want, you can download and inspect the compiled PHAR from here https://github.com/phpstan/phpstan-src/actions/runs/3133984672.

Also, is `'expose-global-functions'` and `'expose-global-classes'` equivalent to previous options `'whitelist-global-functions'` and `'expose-global-classes'`? Thanks.

**Comment by theofidry** [comment]
>Also, is 'expose-global-functions' and 'expose-global-classes' equivalent to previous options 'whitelist-global-functions' and 'expose-global-classes'? Thanks.

I think so, it's also what I wrote in  https://github.com/humbug/php-scoper/releases/tag/0.16.0 so should be 😄

**Comment by ondrejmirtes** [comment]
Had to workaround the bug this way: [phpstan/phpstan-src@`8fcec4b` (#1481)](https://github.com/phpstan/phpstan-src/pull/1481/commits/8fcec4b01bf7a46c24c48d438c5d252a520abcc0) Now it works for me :)

**Comment by theofidry** [comment]
Looking at it, if you take the following code:

```php
<?php declare(strict_types=1);

namespace PhpParser\Builder;

use PhpParser;
use PhpParser\BuilderHelpers;
use PhpParser\Node;
use PhpParser\Node\Name;
use PhpParser\Node\Stmt;
```

With the prefix `_PhpScoperbc29584ffff8` and `'exclude-namespaces' => ['PhpParser']`, it gets scoped into:

```php
namespace PhpParser\Builder;

use _PhpScoperbc29584ffff8\PhpParser;
use PhpParser\BuilderHelpers;
use PhpParser\Node;
use PhpParser\Node\Name;
use PhpParser\Node\Stmt;
```

I assume the `
use _PhpScoperbc29584ffff8\PhpParser` is what is causing you trouble. Unfortunately, I don't think it's neither a bug neither something PHP-Scoper can really do anything about. Indeed, in this specific case `use PhpParser` does not point to a class but a namespace, but there is no way to know that without being aware of the loaded symbols (which PHP-Scoper does not know). So from its perspective, it is scoping the _class_ `PhpParser`, which belongs to the global namespace so is not part of the exclude.

Fortunately, there is a solution still, more elegant than the patcher, which is to add `'exclude-classes' => ['PhpParser']`.
