### ISSUE TITLE
Keep coding style during prefixing process

### ISSUE THREAD

**Issue by matthieuauger** [humbug/php-scoper#7]
Currently, the coding style is not kept when files are processed by the scoper. For exemple

```php
<?php

namespace MyNamespace;

use MyOtherNamespace\MyClass;

class MyClass
{
}
```

is modified like this

```php
<?php

namespace MyNamespace;

use MyOtherNamespace\MyClass;
class MyClass
{
}
```

**Comment by matthieuauger** [comment]
See https://github.com/webmozart/php-scoper/pull/2/files#r43609037

**Comment by theofidry** [comment]
As mentioned in #11, not gonna happen
