### ISSUE TITLE
Error when symfony/phpunit-brige is installed

### ISSUE THREAD

**Issue by Nyholm** [humbug/php-scoper#71]
This is a minor issue. I get the following error
> Argument 1 passed to Humbug\PhpScoper\Scoper\Composer\AutoloadPrefixer::prefixPackageAutoloads() must be of the type array, string given, called in /Users/tobias/.composer/vendor/humbug/php-scoper/src/Scoper/Composer/InstalledPackagesScoper.php on line 75   

Because of https://github.com/symfony/phpunit-bridge/blob/3.4/Tests/DeprecationErrorHandler/fake_vendor/composer/installed.json

**Comment by theofidry** [comment]
Hm maybe it's safer to ignore this kind of failures and continue the scoping...
