### ISSUE TITLE
Fix class_exists

### ISSUE THREAD

**Issue by Nyholm** [humbug/php-scoper#73]
This is not rewritten: 

```php
if (!class_exists('Symfony\\Component\\Yaml\\Parser')) {
     throw new RuntimeException('Unable to load YAML config files as the Symfony Yaml Component is not installed.');
}
```

**Comment by theofidry** [comment]
Indeed, an such strings are a bit tricky as you could very well refer to a partial namespace. If it's in your code, it's easily fixable by changing it to:

```php
if (!class_exists(\Symfony\Component\Yaml\Parser::class)) {
     throw new RuntimeException('Unable to load YAML config files as the Symfony Yaml Component is not installed.');
}
```

provided you are working with PHP 5.5+. If it's third-part code, I think https://github.com/humbug/php-scoper/pull/67 will be the solution
