### ISSUE TITLE
Running composer install is failed in the latest php-scoper repository

### ISSUE THREAD

**Issue by peter279k** [humbug/php-scoper#783]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.18.0-rc.0
| PHP version | 8.1.13
| Platform with version | Ubuntu 18.04
| Github Repo | N/A

Here are the steps to reproduce this issue:

- Cloning the repository with `git clone https://github.com/humbug/php-scoper`
- Running the `php ~/composer.phar install --no-interaction --no-progress --ansi --prefer-dist` command to install PHP dependencies.
- And presenting the following error message:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - humbug/box is locked to version 4.1.0 and an update of this package was not requested.
    - humbug/box 4.1.0 requires humbug/php-scoper ^0.17.3 -> found humbug/php-scoper[dev-main] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
  Problem 2
    - humbug/box 4.1.0 requires humbug/php-scoper ^0.17.3 -> found humbug/php-scoper[dev-main] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
    - paragonie/pharaoh v0.6.0 requires paragonie/sodium_compat ^1.3 -> satisfiable by humbug/box[4.1.0].
    - paragonie/pharaoh is locked to version v0.6.0 and an update of this package was not requested.

```

I think the possible solutions are as follows:

- Using the `"humbug/box": "^4.2",` definition in the `composer.json` file.
- Making the `0.18.x` tag releasing for the `humbug/php-scoper`  and the related `composer install` command will be worked successfully.

**Comment by theofidry** [comment]
It's a know issue due to the circular dependency :/

The work around is to do `source .composer-root-version` first, or do `make vendor_install` which will do it for you
