### ISSUE TITLE
Running make build fails on latest

### ISSUE THREAD

**Issue by aaemnnosttv** [humbug/php-scoper#79]
First of all, thanks for creating this! It solves a real problem for shipping code with bundled dependencies 👍 

I saw on the readme it says that the phar is coming soon, but by the looks of things it seems as though it may be possible to do yourself? I tried building the phar with `make build` but it's looking for `box` which is missing in the `vendor-bin` directory.

```
make build
# everything goes fine until this part...
composer dump-autoload -d build  --classmap-authoritative
Generating optimized autoload files
php -d zend.enable_gc=0 vendor-bin/box/vendor/bin/box build
Could not open input file: vendor-bin/box/vendor/bin/box
make: *** [build] Error 1
```

Am I missing something?

**Comment by theofidry** [comment]
You're welcome!

It's possible to do so, you need to run `composer bin all install` first. I'll add a `Makefile` rule to make it easier and avoid to have to do that.

Note however that the resulting PHAR won't work yet unless you are using the dev-master branch. A new dev tag should be coming shortly after #76

**Comment by padraic** [comment]
We can just add something to composer.json? See: https://github.com/humbug/humbug/blob/master/composer.json#L55

**Comment by theofidry** [comment]
we could, but I don't really like that approach as sometimes you want to manipulate only the root `composer.json` but not the other ones.

I think adding a Makefile rule will be rather easy and more convenient

**Comment by padraic** [comment]
It's noted in `CONTRIBUTING.md` already too. I'm frowning at you @aaemnnosttv :wink: . Just kidding, the extra command is probably unusual enough that it can be noted in the README too as a footnote somewhere.

**Comment by theofidry** [comment]
If added to the makefile you won't ever need it at all though :P

**Comment by padraic** [comment]
Ahh, brain is asleep :grin: Time for a coffee run!

**Comment by aaemnnosttv** [comment]
Thanks guys! The build is breaking in a different way now though :/

It's a rather cryptic error, maybe you guys know what it means?

```
PHP Scoper version 39a2bfe40d9244dd59e4690eda608a0e09afc672

 1743/1853 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  94%make: *** [build] Error 255
```

If I pass `-i` to the build command I see some additional errors

```
PHP Scoper version 39a2bfe40d9244dd59e4690eda608a0e09afc672

 1743/1853 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  94%make: [build] Error 255 (ignored)
composer dump-autoload -d build  --classmap-authoritative
Generating optimized autoload files
php -d zend.enable_gc=0 vendor-bin/box/vendor/bin/box build
Building...

                                                                                                                
  [UnexpectedValueException]                                                                                    
  creating archive "/private/tmp/php-scoper/bin/php-scoper.phar" disabled by the php.ini setting phar.readonly  
                                                                                                                

build [-c|--configuration CONFIGURATION]

make: [build] Error 1 (ignored)
```

I have the repo cloned in `/tmp` in case you're wondering about the path.

**Comment by theofidry** [comment]
Could you try by appending `-d phar.readonly=0`?

```bash
php -d zend.enable_gc=0 -d phar.readonly=0 vendor-bin/box/vendor/bin/box build
```

**Comment by theofidry** [comment]
Fixed by https://github.com/humbug/php-scoper/pull/83 :)
