### ISSUE TITLE
Fatal error: Cannot redeclare humbug_phpscoper_expose_class()

### ISSUE THREAD

**Issue by leoloso** [humbug/php-scoper#809]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.18.1 |
| PHP version | 8.1 |
| Platform with version | MacOS 13 |
| Github Repo | https://github.com/leoloso/PoP |

I'm using PHP-Scoper to scope 2 WordPress plugins. When I install both of them on the same site, I get the following error:

```
Fatal error: Cannot redeclare humbug_phpscoper_expose_class() (previously declared in /app/wordpress/wp-content/plugins/graphql-api/vendor/scoper-autoload.php:23) in /app/wordpress/wp-content/plugins/graphql-api-pro/vendor/scoper-autoload.php on line 27
```

The reason is clear: both plugins define function `humbug_phpscoper_expose_class` in the global space.

Maybe we can append `if(!function_exists('humbug_phpscoper_expose_class')) { ...` when [declaring the function](https://github.com/humbug/php-scoper/blob/f7bd92f2459f1d9a643313f6d324476b0e23e087/src/Autoload/ScoperAutoloadGenerator.php#L44-L50)?

For reference, this is [one of my `scoper.inc.php`](https://github.com/leoloso/PoP/blob/1a7cda04a30e4426fd34516788f8155c7f16849f/ci/scoping/scoper-graphql-api.inc.php).

**Comment by leoloso** [comment]
> Maybe we can append `if(!function_exists('humbug_phpscoper_expose_class')) { ...` when [declaring the function](https://github.com/humbug/php-scoper/blob/f7bd92f2459f1d9a643313f6d324476b0e23e087/src/Autoload/ScoperAutoloadGenerator.php#L44-L50)?

Or as a possibly better solution, maybe this function should not belong to the global space?

For instance, could that function eventually change? What would happen if yet another plugin (which I don't control) also declares this function, and it uses a different version of PHP-Scoper with a different body for that function?

**Comment by leoloso** [comment]
For more info, the generated `scoper-autoload.php` in the first plugin includes this code:

```php
// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
function humbug_phpscoper_expose_class(string $exposed, string $prefixed): void {
    if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
        spl_autoload_call($prefixed);
    }
}
humbug_phpscoper_expose_class('ComposerAutoloaderInit273da6432bdd2a4760f81baa5edeef91', 'PrefixedByPoP\ComposerAutoloaderInit273da6432bdd2a4760f81baa5edeef91');
humbug_phpscoper_expose_class('�', 'PrefixedByPoP\�');
humbug_phpscoper_expose_class('JsonException', 'PrefixedByPoP\JsonException');
humbug_phpscoper_expose_class('ValueError', 'PrefixedByPoP\ValueError');
humbug_phpscoper_expose_class('PhpToken', 'PrefixedByPoP\PhpToken');
humbug_phpscoper_expose_class('Stringable', 'PrefixedByPoP\Stringable');
humbug_phpscoper_expose_class('Attribute', 'PrefixedByPoP\Attribute');
humbug_phpscoper_expose_class('UnhandledMatchError', 'PrefixedByPoP\UnhandledMatchError');
humbug_phpscoper_expose_class('CastToType', 'PrefixedByPoP\CastToType');
```

And for the 2nd plugin:

```php
// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
function humbug_phpscoper_expose_class(string $exposed, string $prefixed): void {
    if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
        spl_autoload_call($prefixed);
    }
}
humbug_phpscoper_expose_class('ComposerAutoloaderInit89cbc2fda26b6381875b47bf0ef5ef0b', 'PrefixedByPoPPRO\ComposerAutoloaderInit89cbc2fda26b6381875b47bf0ef5ef0b');
```

**Comment by theofidry** [comment]
Ha I didn't think of this case. I think it makes sense to wrap the function declaration in a `if(!function_exists())` statement.

>Or as a possibly better solution, maybe this function should not belong to the global space?

Technically possible, but a bit annoying in this specific case. At the very least it's more boiler-template so I wanted to avoid it.

>For instance, could that function eventually change? What would happen if yet another plugin (which I don't control) also declares this function, and it uses a different version of PHP-Scoper with a different body for that function?

If it really comes to this, then indeed I'll have to introduce a namespace for it. But as an end-user you should not be affected. Also note that this function is internal, maybe I should prefix it with `_`...
