### ISSUE TITLE
Unable to determine what Guzzle version is installed

### ISSUE THREAD

**Issue by gabripuglia** [humbug/php-scoper#838]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.17.5
| PHP version | 7.4.3

I try to use php scoper for a plugin developed to send cloudwatch logs directly to the cloudwatch agent.

These are the steps followed:
- composer update
- composer require humbug/php-scoper
- .\vendor\bin\php-scoper init
- added prefix and created src directory with the exclude php file
- .\vendor\bin\php-scoper add-prefix
- set new vendor dir in config.json
- include new autoloader
- composer update

The software works but when i try to launch the function to init the aws client, a new exception is triggered: Unable to determine what Guzzle version is installed.

I tried, also, the command .\vendor\bin\php-scoper add-prefix --no-config --force

**I noticed the same behavior in both windows or mac os (with the same php cli version 7.4.3)**

**Comment by m-ovs** [comment]
Hi. I found this issue because I also have a problem with Guzzle6 vs Guzzlee7 in the same project. But I got more advances error 
```
 PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\guzzlehttp\guzzle\src\HandlerStack.php:42
Stack trace:
#0 C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\guzzlehttp\guzzle\src\Client.php(65): GuzzleHttp\HandlerStack::create()
#1 C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\aws\aws-sdk-php\src\Handler\GuzzleV6\GuzzleHandler.php(26): GuzzleHttp\Client->__construct()
#2 C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\aws\aws-sdk-php\src\functions.php(279): Aws\Handler\GuzzleV6\GuzzleHandler->__construct()
#3 C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\aws\aws-sdk-php\src\ClientResolver.php(652): Aws\default_http_handler()
#4 C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\aws\aws-sdk-php\src\Clien in C:\Users\Movs\git\dbeaver-website\wordpress\wp-content\plugins\s3-bucket-listing\vendor\guzzlehttp\guzzle\src\HandlerStack.php on line 42

```

Next I found that in project which uses Guzzle6 this file 'vendor/guzzlehttp/guzzle/src/functions.php' contains some global functions in the namespace /Guzzle and somehow it was not autoloaded by composer. Including this file manually solved the problem, but this looks like an issue.
`require_once ( 'vendor/guzzlehttp/guzzle/src/functions.php');`

**Comment by theofidry** [comment]
Note to self: retry this with PHP-Scoper 0.18.3.

**Comment by theofidry** [comment]
As shown in #867, it has been fixed.
