### ISSUE TITLE
Fails to modify namespaces with php 8(.2.6)?

### ISSUE THREAD

**Issue by MarkRS-UK** [humbug/php-scoper#839]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.18.2
| PHP version | 8.2.6 , Zend Engine v4.2.6, Zend OPcache v8.2.6, Xdebug v3.2.1
| Platform with version | Fedora 38
| Github Repo | - 

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
 <?php
 
 declare(strict_types=1);
 
 use Isolated\Symfony\Component\Finder\Finder;
 
 return [
    'finders' => [
        /*
        Finder::create()->files()->in('src'), */
        Finder::create()
            ->files()
            ->ignoreVCS(true)
            ->notName('/LICENSE|.*\\.md|.*\\.dist|Makefile|composer\\.json|composer\\.lock/')
            ->exclude([
                'tmpl',
                'forms',
                'services',
                'src',
                'sql',
                'presets',
            ])
            ->in('vendor') /*,
        Finder::create()->append([
            'composer.json',
        ]), */
        
    ] ];

 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
/usr/bin/php-scoper.phar add-prefix -p mm -o ./buildmm
 > output
Output reports all files processed.  They are produced, they have not been changed.
 ```
</details>

**Comment by MarkRS-UK** [comment]
Sorry, just me being dumb :(

**Comment by theofidry** [comment]
Did you manage to find what the issue was?

**Comment by MarkRS-UK** [comment]
I misunderstood how to exclude files, so I excluded what I was trying to include.
I still haven't got it quite down; I'm now including everything but just delete what I don't want, and I had to add code to LoadClass (to remove my prefix in the loadFile line) and add my prefix to the line that loads LoadClass.
