### ISSUE TITLE
Incosistent scope/namespacing of InstalledVersions class

### ISSUE THREAD

**Issue by suabahasa** [humbug/php-scoper#841]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | > 0.18.0
| PHP version | > 7.4.0
| Platform with version | Ubuntu/Windows
| Github Repo | https://github.com/orgrosua/yabe-webfont

I have a WordPress plugin named "Yabe Webfont" that uses the php-scoper to build the release file.

The[ `Composer\InstalledVersions` class](https://github.com/orgrosua/yabe-webfont/blob/46e6510568cbad15093756f2ffa730bd192eef02/vendor/composer/InstalledVersions.php#L12) was namespace-ed on its file, but it's not on the [`autoload_classmap.php`](https://github.com/orgrosua/yabe-webfont/blob/46e6510568cbad15093756f2ffa730bd192eef02/vendor/composer/autoload_classmap.php#L10) and [`autoload_static.php`](https://github.com/orgrosua/yabe-webfont/blob/46e6510568cbad15093756f2ffa730bd192eef02/vendor/composer/autoload_static.php#L112) files.

This leads to fatal errors when two libraries use composer.
```
Fatal error: Cannot declare class _YabeWebfont\Composer\InstalledVersions, because the name is already in use in /home/wordpress_website/public_html/wp-content/plugins/yabe-webfont/vendor/composer/InstalledVersions.php on line 25
```

**To reproduce the issue:**
- You can create a temporary WordPress site with https://instawp.com/ (its free account is enough)
- Install the Yabe Webfont plugin (the plugin use php-scoper) from https://wordpress.org/plugins/yabe-webfont/
- Install the WP Activity Log plugin (this plugin uses the composer, too) from https://wordpress.org/plugins/wp-security-audit-log
- Activate both plugins from the wp-admin dashboard

Once both are activated, fatal errors will happen.

The workaround is to add the scope (`_YabeWebfont\\`) on the `autoload_classmap.php` and `autoload_static.php` files.

```php
return array(
    '_YabeWebfont\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
```

```php
public static $classMap = array (
    '_YabeWebfont\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
);
```

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
 <?php

declare(strict_types=1);

use Isolated\Symfony\Component\Finder\Finder;

// You can do your own things here, e.g. collecting symbols to expose dynamically
// or files to exclude.
// However beware that this file is executed by PHP-Scoper, hence if you are using
// the PHAR it will be loaded by the PHAR. So it is highly recommended to avoid
// to auto-load any code here: it can result in a conflict or even corrupt
// the PHP-Scoper analysis.

// $timestamp = date('Ymd');

$wp_classes   = json_decode(file_get_contents('deploy/php-scoper-wordpress-excludes-master/generated/exclude-wordpress-classes.json'));
$wp_functions = json_decode(file_get_contents('deploy/php-scoper-wordpress-excludes-master/generated/exclude-wordpress-functions.json'));
$wp_constants = json_decode(file_get_contents('deploy/php-scoper-wordpress-excludes-master/generated/exclude-wordpress-constants.json'));

/**
 * @see https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#polyfills
 */
$polyfillsBootstraps = array_map(
    static fn (SplFileInfo $fileInfo) => $fileInfo->getPathname(),
    iterator_to_array(
        Finder::create()
            ->files()
            ->in(dirname(__DIR__) . '/vendor/symfony/polyfill-*')
            ->name('bootstrap*.php'),
        false,
    ),
);

$polyfillsStubs = array_map(
    static fn (SplFileInfo $fileInfo) => $fileInfo->getPathname(),
    iterator_to_array(
        Finder::create()
            ->files()
            ->in(dirname(__DIR__) . '/vendor/symfony/polyfill-*/Resources/stubs')
            ->name('*.php'),
        false,
    ),
);

return [
    // The prefix configuration. If a non null value is be used, a random prefix
    // will be generated instead.
    //
    // For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#prefix
    // 'prefix' => '_Yabe' . $timestamp,
    'prefix' => '_YabeWebfont',

    // By default when running php-scoper add-prefix, it will prefix all relevant code found in the current working
    // directory. You can however define which files should be scoped by defining a collection of Finders in the
    // following configuration key.
    //
    // This configuration entry is completely ignored when using Box.
    //
    // For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#finders-and-paths
    // 'finders' => [
    //     Finder::create()->files()->in('src'),
    //     Finder::create()->files()->in('templates'),
    //     Finder::create()
    //         ->files()
    //         ->ignoreVCS(true)
    //         ->notName('/LICENSE|.*\\.md|.*\\.dist|Makefile|composer\\.json|composer\\.lock/')
    //         ->exclude([
    //             'doc',
    //             'test',
    //             'test_old',
    //             'tests',
    //             'Tests',
    //             'vendor-bin',
    //         ])
    //         ->in('vendor'),
    //     Finder::create()->append([
    //         'composer.json',
    //         'wakaloka-winden.php',
    //     ]),
    // ],

    // List of excluded files, i.e. files for which the content will be left untouched.
    // Paths are relative to the configuration file unless if they are already absolute
    //
    // For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#patchers
    'exclude-files' => [
        // 'src/a-whitelisted-file.php',

        ...$polyfillsBootstraps,
        ...$polyfillsStubs,
    ],

    // When scoping PHP files, there will be scenarios where some of the code being scoped indirectly references the
    // original namespace. These will include, for example, strings or string manipulations. PHP-Scoper has limited
    // support for prefixing such strings. To circumvent that, you can define patchers to manipulate the file to your
    // heart contents.
    //
    // For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#patchers
    // 'patchers' => [
    //     static function (string $filePath, string $prefix, string $contents): string {
    //         // Change the contents here.

    //         return $contents;
    //     },
    // ],

    // List of symbols to consider internal i.e. to leave untouched.
    //
    // For more information see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#excluded-symbols
    'exclude-namespaces' => [
        // 'Acme\Foo'                     // The Acme\Foo namespace (and sub-namespaces)
        // '~^PHPUnit\\\\Framework$~',    // The whole namespace PHPUnit\Framework (but not sub-namespaces)
        // '~^$~',                        // The root namespace only
        // '',                            // Any namespace,

        'Yabe\Webfont',
        'Breakdance',
        'WP_CLI',
        'Symfony\Polyfill',
    ],
    'exclude-classes' => array_merge(
        $wp_classes,
        [
            'WP_CLI',
            'WP_CLI_Command',
            // 'ReflectionClassConstant',

            // as our file is not namespaced, we need to exclude the class name
            // 'YABE_WEBFONT',

            // try with expose-classes
        ]
    ),
    'exclude-functions' => array_merge(
        $wp_functions,
        [
            // 'mb_str_split',
            'Breakdance\Fonts\registerFont',
            'bricks_is_builder',

            'wp_cache_flush',
            'rocket_clean_domain',
            'wp_cache_clear_cache',
            'w3tc_flush_all',
            'wpfc_clear_all_cache',
        ]
    ),
    'exclude-constants' => array_merge(
        $wp_constants,
        [
            // Symfony global constants
            '/^SYMFONY\_[\p{L}_]+$/',

            'WP_CONTENT_DIR',
            'WP_CONTENT_URL',
            'ABSPATH',
            'WPINC',
            'WP_DEBUG_DISPLAY',
            'WPMU_PLUGIN_DIR',
            'WP_PLUGIN_DIR',
            'WP_PLUGIN_URL',
            'WPMU_PLUGIN_URL',
            'MINUTE_IN_SECONDS',
            'HOUR_IN_SECONDS',
            'DAY_IN_SECONDS',
            'MONTH_IN_SECONDS',
            'debugger',

            'YABE_WEBFONT_FILE',
            'YABE_WEBFONT_OPTION_NAMESPACE',
            'YABE_WEBFONT_HOSTED_WAKUFONT',
            'YABE_WEBFONT_EDD_STORE',
            'YABE_WEBFONT_REST_NAMESPACE',

            'SHOW_CT_BUILDER',
            'CWICLY_VERSION',
            'BRICKS_VERSION',
            '__BREAKDANCE_VERSION',
            'SLINGBLOCKS_PLUGIN_VERSION',
        ]
    ),

    // List of symbols to expose.
    //
    // For more information see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#exposed-symbols
    'expose-global-constants' => false,
    'expose-global-classes' => false,
    'expose-global-functions' => false,
    'expose-namespaces' => [
        // 'Acme\Foo'                     // The Acme\Foo namespace (and sub-namespaces)
        // '~^PHPUnit\\\\Framework$~',    // The whole namespace PHPUnit\Framework (but not sub-namespaces)
        // '~^$~',                        // The root namespace only
        // '',                            // Any namespace
    ],
    'expose-classes' => [
        // here we expose our class, because we can't make php-scoper to not namespace it
        'YABE_WEBFONT',
    ],
    'expose-functions' => [],
    'expose-constants' => [],
];

 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ command
 > output
 ```
</details>

**Comment by suabahasa** [comment]
This issue was not spotted if there are no two libraries using composer because this code on the `scoper-autoload.php` file
```php
// Ensure InstalledVersions is available
$installedVersionsPath = __DIR__.'/composer/InstalledVersions.php';
if (file_exists($installedVersionsPath)) require_once $installedVersionsPath;
```

It was spotted when I [upgraded](https://github.com/orgrosua/yabe-webfont/compare/1.0.34...1.0.41#diff-5dd0810de425a84aa2fc2a0ad05028ccbc1304193f5a0c04962a059abd85db0f) the php-scoper version from `0.17.x` to `0.18.3`.

**Comment by suabahasa** [comment]
Turn out that I run `composer dump-autoload --working-dir "$RESULT_DIRECTORY" --ansi --classmap-authoritative --no-dev` after run the php-scoper.


So I remove it, then  now, different fatal errors happen
```
Fatal error: Uncaught Error: Class "_YabeWebfont\Composer\Autoload\ClassLoader" not found in /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-content/plugins/yabe-webfont-pro-2.0.43/vendor/composer/autoload_real.php:25 Stack trace: #0 /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-content/plugins/yabe-webfont-pro-2.0.43/vendor/autoload.php(21): _YabeWebfont\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7::getLoader() #1 /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-content/plugins/yabe-webfont-pro-2.0.43/vendor/scoper-autoload.php(10): require_once('...') #2 /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-content/plugins/yabe-webfont-pro-2.0.43/yabe-webfont.php(27): require_once('...') #3 /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-admin/includes/plugin.php(2314): include_once('...') #4 /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape() #5 {main} thrown in /home/bopumazoba5445/web/d-elephant-dexi.instawp.xyz/public_html/wp-content/plugins/yabe-webfont-pro-2.0.43/vendor/composer/autoload_real.php on line 25
```

**Comment by suabahasa** [comment]
For the fatal error `Fatal error: Uncaught Error: Class "_YabeWebfont\Composer\Autoload\ClassLoader" not found`,
The classes name in a literal string doesn't prefix properly.

## File: vendor/composer/autoload_real.php

**expected**
```diff
-        if ('Composer\Autoload\ClassLoader' === $class) {
+        if ('_YabeWebfont\\Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }

@@ -21,31 +20,24 @@ public static function getLoader()

-        spl_autoload_register(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'), true, true);
-        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
-        spl_autoload_unregister(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'));
+        \spl_autoload_register(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'), \true, \true);
+        self::$loader = $loader = new \_YabeWebfont\Composer\Autoload\ClassLoader(\dirname(__DIR__));
+        \spl_autoload_unregister(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'));

```

**actual**
```diff
-        if ('Composer\Autoload\ClassLoader' === $class) {
+        if ('Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }

@@ -21,31 +20,24 @@ public static function getLoader()

-        spl_autoload_register(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'), true, true);
-        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
-        spl_autoload_unregister(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'));
+        \spl_autoload_register(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'), \true, \true);
+        self::$loader = $loader = new \_YabeWebfont\Composer\Autoload\ClassLoader(\dirname(__DIR__));
+        \spl_autoload_unregister(array('ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'));

```

**Comment by theofidry** [comment]
@suabahasa hacking the autoloader looks very suspicious to me. Was the composer autoloader dumped after the scoping process?

**Comment by suabahasa** [comment]
> For the fatal error `Fatal error: Uncaught Error: Class "_YabeWebfont\Composer\Autoload\ClassLoader" not found`,
> The classes name in a literal string doesn't prefix properly.
> 
> ## File: vendor/composer/autoload_real.php
> 
> **expected**
> ```diff
> -        if ('Composer\Autoload\ClassLoader' === $class) {
> +        if ('_YabeWebfont\\Composer\\Autoload\\ClassLoader' === $class) {
>             require __DIR__ . '/ClassLoader.php';
>         }
> 
> @@ -21,31 +20,24 @@ public static function getLoader()
> 
> -        spl_autoload_register(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'), true, true);
> -        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
> -        spl_autoload_unregister(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'));
> +        \spl_autoload_register(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'), \true, \true);
> +        self::$loader = $loader = new \_YabeWebfont\Composer\Autoload\ClassLoader(\dirname(__DIR__));
> +        \spl_autoload_unregister(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'));
> 
> ```
> 
> **actual**
> ```diff
> -        if ('Composer\Autoload\ClassLoader' === $class) {
> +        if ('Composer\\Autoload\\ClassLoader' === $class) {
>             require __DIR__ . '/ClassLoader.php';
>         }
> 
> @@ -21,31 +20,24 @@ public static function getLoader()
> 
> -        spl_autoload_register(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'), true, true);
> -        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
> -        spl_autoload_unregister(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'));
> +        \spl_autoload_register(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'), \true, \true);
> +        self::$loader = $loader = new \_YabeWebfont\Composer\Autoload\ClassLoader(\dirname(__DIR__));
> +        \spl_autoload_unregister(array('ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'));
> 
> ```
> 
> ## Workaround: php-scoper config
> 
> ```php
> <?php
> 
> 
> return [
> 
>     'patchers' => [
>         /**
>          * @see https://github.com/humbug/php-scoper/issues/841
>          */
>         static function (string $filePath, string $prefix, string $contents): string {
>             if (preg_match('/vendor\/composer\/autoload_real\.php$/', $filePath)) {
>                 return preg_replace(
>                     [
>                         "/'Composer\\\\\\\\Autoload\\\\\\\\ClassLoader'/",
>                         "/spl_autoload_unregister\(array\('ComposerAutoloaderInit/",
>                     ],
>                     [
>                         "'{$prefix}\\\\\\\\Composer\\\\\\\\Autoload\\\\\\\\ClassLoader'",
>                         "spl_autoload_unregister(array('{$prefix}\\\\\\\\ComposerAutoloaderInit",
>                     ],
>                     $contents
>                 );
>             }
> 
>             return $contents;
>         },
>     ],
> 
> ],
> ```

@theofidry 
the actual issue are on this comment.

It's not a hack, but workaround.

**Comment by theofidry** [comment]
> The classes name in a literal string doesn't prefix properly.

But the file you are showing is `vendor/composer/autoload.php`: the Composer files should not be prefixed, or rather they are, but you are expected to run `composer dump-autoload` afterwards to correct them (as per https://github.com/humbug/php-scoper#without-box).

**Comment by suabahasa** [comment]
> But the file you are showing is `vendor/composer/autoload.php`: the Composer files should not be prefixed, or rather they are, but you are expected to run `composer dump-autoload` afterward to correct them (as per https://github.com/humbug/php-scoper#without-box).

`vendor/composer/autoload.php` is the trace of the error, but the actual issue is because the `vendor/composer/autoload_real.php` file's content is not prefixed consistently. Check the git diff on my previous reply between expected and actual.

I have run `composer dump-autoload` and it solved the original issue, so the current valid issue is on this reply https://github.com/humbug/php-scoper/issues/841#issuecomment-1608835294

**Comment by theofidry** [comment]
>I have run composer dump-autoload and it solved the original issue

There you go :)

>but the actual issue is because the vendor/composer/autoload_real.php file's content is not prefixed consistently.

Maybe I was not clear before, the reason why you _need_ to dump the autoloader is _because_ this file cannot be prefixed consistently.

Prefixing the whole Composer autoloader is hard and bound to break at the slightest Composer internal change. Given that it actually has nothing that need prefixing, it actually is best to leave it alone. If you wanted to prefix the project without having to dump the autoload you could do so by excluding all the Composer autoload related files. But I found that it's easier to just scope the whole project and dump the autoload again.

So cool that your case is fixed, and the actual root of the issue with `autoload_real.php` is unfortunately a "won't fix" for the reasons stated above

**Comment by suabahasa** [comment]
If `autoload_real.php` should not be prefixed, then with plain php-scoper config, it is still prefixed as shown in the `actual` section below.


## File: vendor/composer/autoload_real.php

**actual**
```diff

@@ -21,31 +20,24 @@ public static function getLoader()

-        spl_autoload_register(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'), true, true);
-        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
-        spl_autoload_unregister(array('ComposerAutoloaderInitdc4ff1e5b947ba57f43dd1c38e03246f', 'loadClassLoader'));
+        \spl_autoload_register(array('_YabeWebfont\\ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'), \true, \true);
+        self::$loader = $loader = new \_YabeWebfont\Composer\Autoload\ClassLoader(\dirname(__DIR__));
+        \spl_autoload_unregister(array('ComposerAutoloaderInit8408a7d92db31260d670a903f5fc8eb7', 'loadClassLoader'));

```

Whether it should not be prefixed or not, the issue was raised because it was inconsistent.

**Comment by theofidry** [comment]
>If autoload_real.php should not be prefixed, then with plain php-scoper config, it is still prefixed as shown in the actual section below.

"it should not" kinda depends here.

As mentioned above, if your goal is to have it work without executing a `composer dump-autoload` afterwards, then indeed it must not be touched. But this is a project/user specific and you would need to experiment with the `exclude-files` setting.

Otherwise, it will be prefixed, but it doesn't matter as when you dump the autoload it is overridden, so why bother.

Granted the whole thing is a bit confusing, but given that you do need manual steps anyway to make sure you include `scoper-autoload.php` rather than `autoload.php`, this allows to keep things simple internally.
