### ISSUE TITLE
scoper-autoload.php doesn't support PHP 5.6

### ISSUE THREAD

**Issue by marekdedic** [humbug/php-scoper#842]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.18.3
| PHP version | 5.6
| Platform with version | all
| Github Repo | [- ](https://github.com/skaut/skaut-google-drive-gallery/)

Hi,
I am using PHP-scoper for packaging a WordPress plugin, so I don't really get much control over which PHP versions it will be running with. Recently I got reports of ` syntax error, unexpected ‘:’, expecting ‘{‘` in the `scoper-autoload.php` file and was surprised to find that it contains return type annotations, possibly as an artifact from the build process. I tried to look for info about supported runtime php versions in the project, but couldn't find any

I assume composer minimum version is the version of PHP php-scoper runs on, but the output would respect the source code it processes...

**Comment by mikey242** [comment]
Hi @marekdedic. The latest scoper version requires **php 8.1** minimum. If you set the php version in your composer.json and require a new library, it will download the latest version that supports that version of php.

`
"config": {
    "platform": {
        "php": 5.6
    }
}
`

However even the oldest version of scoper requires at least **php 7**. The easiest way to see the supported php version is to check out the package on [packagist.org](https://packagist.org/packages/humbug/php-scoper#0.18.3) and see what it says there under **requires**. You can also find this information in the **composer.json** file for the project.

**Comment by marekdedic** [comment]
Hi,
hmm, I'll try to expand on my last paragraph - I see 2 different PHP version requirements potentially be at play here:

- the minimum version on which php-scoper **itself** can run - I presume that this is what I see in [packagist](https://packagist.org/packages/humbug/php-scoper) and it indeed never contained 5.6.
- The minimum version on which the **output** of php-scoper can run - I am pretty confident I did previously use the output of php-scoper even on 5.6, but I don't see that listed anywhere

In my case, these 2 can differ wildly - I use php-scoper as part of a build process for WordPress plugins - I build them on my machine or in CI, where I can configure whatever version of PHP I want and this is when php-scoper actually runs. I then distribute the build output (the WP plugin) to users - I have almost no control over where they run the code then.

I am not arguing for lowering the first one, just the second one - I feel like type annotations don't add that much to generated code anyways and removing them would help my use case.

**Comment by theofidry** [comment]
Since PHP-Scoper does not orchestrate a Composer binary (unlike Box) I am happy to add support for this. AFAICS it should only be a matter of adapting the dumped scoper-autoload.
