### ISSUE TITLE
The "src" directory does not exist.

### ISSUE THREAD

**Issue by TerrePorter** [humbug/php-scoper#843]
Hello,

I am just checking to see if anyone else has run into this error.

```
$ php-scoper add-prefix
In Finder.php line 638:
  The "src" directory does not exist.
```

This is the composer.json,
```
{   
    "autoload": {
        "psr-4": {
            "ZoomLtr\\": "library"
        }
    },
    "require": {
        "tymon/jwt-auth": "^1.0",
        "guzzlehttp/guzzle": "~6.0",
        "firebase/php-jwt": "^5.0",
        "nesbot/carbon": "^2.32"
    }
}
```

Could it be because the php-scoper needs to run on php8 and some of these packages won't run on php8. I assumed it didn't matter since I thought the php-scoper did not actually run the code, but I could be wrong about that.

I don't have any src directory in my project code. I am assuming this is coming from something in the vendor directory.

Any ideas?

**Comment by theofidry** [comment]
Closing as not enough feedback to act on. If you still have the problem don't hesitate to open a new issue for it.
