### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.28 and ,Class 'Composer\InstalledVersions' not found errors

### ISSUE THREAD

**Issue by devloppora** [humbug/php-scoper#845]
The command **"composer update"** generates this error for me: **"Class 'Composer\InstalledVersions' not found"**, but I have composer version 2.0 and PHP 8.0.20. Normally, I want to add the command "php artisan queue:work" in the Hostinger SSH command line to manage the queues. However, this command generates the error "**Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.28."** So, I ran "composer update", which generated this error "Class 'Composer\InstalledVersions' not found".

**Comment by theofidry** [comment]
Hi @devloppora, could it be possible to get more information such as the error stack trace, the composer.json file used and the PHP-Scoper version?
