### ISSUE TITLE
Specify the prefix

### ISSUE THREAD

**Issue by Nyholm** [humbug/php-scoper#90]
Is there anyway I can specify the prefix that is being used? 
I have an idea that I may be able to to a search and replace on the source code. 

Background: Im trying to run the scoper on Symfony source.

**Comment by theofidry** [comment]
Yep, with the option `--prefix` or `-p`

**Comment by Nyholm** [comment]
Good. I will try that tomorrow.

**Comment by Nyholm** [comment]
It works great with the --prefix option. 

FYI, here is what I do to make sure Symfony works with a new prefix. 

```bash
php -d zend.enable_gc=0 -d xdebug.max_nesting_level=500 $(PHPSCOPER) add-prefix --prefix PharTranslation --force
find ./build/vendor/symfony -type f -exec perl -pi -e 's/(?:PharTranslation\\+)?Symfony(\\+)/PharTranslation\1Symfony\1/g' {} \;
```

Im still having some issues with Twig though..

**Comment by Nyholm** [comment]
I've updated my last answer and the issue title to allow others to find this issue.
 
It do works now with Symfony3.3.
