### ISSUE TITLE
There are no phar philes in github releases :( 

### ISSUE THREAD

**Issue by mejta** [humbug/php-scoper#912]
## Bug report

Hello @theofidry, 

Thank you very much for maintaining PHP Scoper; it's a super-useful tool for scoping the dependencies. Unfortunately, I have an issue with the automation of the dependencies, as the latest release lacks the generated PHAR file. Can you please add that? Thank you very much!

Dan

**Comment by theofidry** [comment]
Hi! Thanks for the report. Looks like the CI configuration for the release process had to be adapted #923. I've just released [0.18.9](https://github.com/humbug/php-scoper/releases/tag/0.18.9) and the PHAR is there!
