### ISSUE TITLE
Is scoper-autoload.php discarded from the php-scoper?

### ISSUE THREAD

**Issue by bilal-ahmed-wpb** [humbug/php-scoper#953]
### Problem

- `scoper-autoload.php` file not generated as expected.

### Steps Taken

1. **Initialization**
   - Initialized PHP-Scoper using `php-scoper init`.
2. **Configuration**
   - Set prefix to `MyNameSpace`.
   - Specified finder targeting vendor dependencies.
3. **Prefixing**
   - Applied prefixing with `php-scoper add-prefix`.
4. **Autoloader Generation**
   - Moved to `build` directory.
   - Attempted to generate autoloader with `composer dump-autoload`.

### Dependencies

- `google/apiclient`
- `google/analytics-admin`
- `google/analytics-data`

### Request

- Guidance on troubleshooting the missing file and correct PHP-Scoper usage.

### scoper.inc.php code
```php
<?php

declare(strict_types=1);
namespace MyNameSpace;

// scoper.inc.php
use MyNameSpace\Isolated\Symfony\Component\Finder\Finder;
return [
    'prefix' => 'MyNameSpace',
    // string|null
    'output-dir' => null,
    // string|null
    'finders' => [],
    // list<Finder>
    'patchers' => [],
    // list<callable(string $filePath, string $prefix, string $contents): string>
    'exclude-files' => [],
    // list<string>
    'exclude-namespaces' => [],
    // list<string|regex>
    'exclude-constants' => [],
    // list<string|regex>
    'exclude-classes' => [],
    // list<string|regex>
    'exclude-functions' => [],
    // list<string|regex>
    'expose-global-constants' => false,
    // bool
    'expose-global-classes' => false,
    // bool
    'expose-global-functions' => false,
    // bool
    'expose-namespaces' => [],
    // list<string|regex>
    'expose-constants' => [],
    // list<string|regex>
    'expose-classes' => [],
    // list<string|regex>
    'expose-functions' => [],
];

**Comment by theofidry** [comment]
The only reason I can think of is if [this condition](https://github.com/humbug/php-scoper/blob/main/src/Console/ConsoleScoper.php#L144) is skipped, which would be weird.

Unfortunately I cannot help without a more concrete reproducer or idea of what is contained in the `build` directory, but my guess would be that the finder configuration is incorrect or that the files you expected to scope were not present in the first place (missing a composer install or smth?)

**Comment by bilal-ahmed-wpb** [comment]
But my question still there that scoper-autoload.php is made or is this thing removed?

**Comment by bilal-ahmed-wpb** [comment]
Can I be guided how to namespace the entire vendor? For the following dependencies:

- google/apiclient
- google/analytics-admin
- google/analytics-data

In terms that my plugin basically conflicts with the plugin having these same mentioned libraries. It would be quite helpful if I just get the proper way of scoping the vendor folder.
composer require google/apiclient
composer require google/analytics-admin
composer require google/analytics-data

I will really appreciate the help if provided or some guidance hint or point.

**Comment by theofidry** [comment]
>Can I be guided how to namespace the entire vendor?

This is not really how it should be used. The idea of PHP-Scoper is to make _your application_ scoped, not an arbitrary package it uses.

As for an example, although I am not sure if that will really help, you can check `fixtures/set028-symfony`:

- composer install
- scoper add-prefix --out-dir=dist
- composer dump-autoload --working-dir=dist

And that should be it.

**Comment by bilal-ahmed-wpb** [comment]
The most interesting fact is that on excluding some specific namespaces of the above dependencies my code works but there is still the chance of conflict with other plugins. Moreover the way you provided, I did same, and once my entire library was not namespace with anything and was scoped same as it was before using php-scoper.

**Comment by bilal-ahmed-wpb** [comment]
When the scoping was in process I checked the build folder, the namespace was there but as the scope process finished and I ran composer dump-autoload and again check the build folder no namespace was there and all the build folder was same as before running php-scoper

**Comment by theofidry** [comment]
Sure but if for example you have all your files in scoper.inc.php`exclude-files` then that is expected. You do need to adjust those configuration values. See https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#finders-and-paths and https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#excluded-files.

**Comment by bilal-ahmed-wpb** [comment]
I have not excluded any file or namespace

**Comment by bilal-ahmed-wpb** [comment]
Moreover when I use the finder the autoloading issue occurs

**Comment by saas786** [comment]
Although my prefixed code does work with `autoload.php`, I no longer see `scoper-autoload.php` similar to @bilal-ahmed-wpb.

**Comment by theofidry** [comment]
Could you provide an actual reproducer?

**Comment by bilal-ahmed-wpb** [comment]
This is the original one
```
<?php

declare (strict_types=1);

// scoper.inc.php
use Isolated\Symfony\Component\Finder\Finder;
return [
    'prefix' => 'MyPlugin',
    // string|null
    'output-dir' => null,
    // string|null
    'finders' => [],
    // list<Finder>
    'patchers' => [],
    // list<callable(string $filePath, string $prefix, string $contents): string>
    'exclude-files' => [],
    // list<string>
    'exclude-namespaces' => [],
    // list<string|regex>
    'exclude-constants' => [],
    // list<string|regex>
    'exclude-classes' => [],
    // list<string|regex>
    'exclude-functions' => [],
    // list<string|regex>
    'expose-global-constants' => \false,
    // bool
    'expose-global-classes' => \false,
    // bool
    'expose-global-functions' => \false,
    // bool
    'expose-namespaces' => [],
    // list<string|regex>
    'expose-constants' => [],
    // list<string|regex>
    'expose-classes' => [],
    // list<string|regex>
    'expose-functions' => [],
];
```
The following are the dependencies on which I am running php-scoper with above configuration:
**composer require google/apiclient
composer require google/analytics-admin
composer require google/analytics-data**

**Comment by bilal-ahmed-wpb** [comment]
@saas786 can you provide me the scoper.inc.php configuration or guide me with the above provided config of mine?

**Comment by theofidry** [comment]
@bilal-ahmed-wpb 

- create a new project directory
- copy the content of `scoper.inc.php` that you provided
- run:

```shell
echo '{}' > composer.json
composer require google/apiclient
composer require google/analytics-admin
composer require google/analytics-data
```

- download PHP-Scoper PHAR from https://github.com/humbug/php-scoper/releases/tag/0.18.11
- execute `php-scoper.phar add-prefix`

<hr/>

When I check `build` I see everything prefixed and there is a `vendor/scoper-autoload.php` in there. So if the above does not work please provide a reproducer in a dedicated repository or `Dockerfile`.

**Comment by bilal-ahmed-wpb** [comment]
I have to place the  PHP-Scoper PHAR in the directory where we are performing the above operations? As current directory is
vendor
composer.json
composer.lock
php-scoper.phar
scoper.inc.php
I am using Windows 11 and previously I was using the composer way. php-scoper add-prefix

**Comment by theofidry** [comment]
>I have to place the PHP-Scoper PHAR in the directory where we are performing the above operations?

No, only the _working directory_ should matter.

**Comment by bilal-ahmed-wpb** [comment]
When I

> * execute `php-scoper.phar add-prefix`
I get php-scoper phar not found. Does this need any special setup?

**Comment by theofidry** [comment]
it's the PHP-Scoper PHAR you downloaded just before. You can find more details or options [there](https://github.com/humbug/php-scoper/blob/main/docs/installation.md#github) and need to adjust the command to reference that PHP-Scoper binary installed.

**Comment by saas786** [comment]
This is the config I have: https://github.com/saas786/disabler/blob/master/bin-dev/php-scoper/scoper.inc.php

**Comment by theofidry** [comment]
@saas786 I cannot see anything wrong from the config so if you want me to have a look please provide an actual reproducer. I wouldn't know how to execute your project, what options you pass to your command or even install the dependencies (since it looks like you have some private or locally linked ones).

**Comment by bilal-ahmed-wpb** [comment]
I will for sure provide you the reproducer. Is git access ok ? Or I have to provide you a docker image?

**Comment by theofidry** [comment]
git is fine

**Comment by theofidry** [comment]
Sorry I couldn't check it earlier.

@saas786 from the repo you gave me:

- git clone git@github.com:saas786/disabler.git
- cd disabler
- composer install
- composer prefix

In your generated `disabler-prefixed` I do see `vendor/scoper-autoload.php`;

**Comment by theofidry** [comment]
If you have another case, with a clear and simple reproducer, showing a problem there, please open a new issue.

**Comment by saas786** [comment]
> If you have another case, with a clear and simple reproducer, showing a problem there, please open a new issue.

@theofidry 

I followed your steps, but unfortunately, it did not generate `vendor/scoper-autoload.php` for me.

I'm not sure what could be causing this issue. Could it be due to using Windows?


![explorer_CYUSpiKFSQ](https://github.com/humbug/php-scoper/assets/1642796/c246f6a4-850c-4344-8458-1174e9e0686a)

**Comment by theofidry** [comment]
>I'm not sure what could be causing this issue. Could it be due to using Windows?

I wouldn't think so, but I'm not using Windows so can't guarantee it. You could try to put a break point [here](https://github.com/humbug/php-scoper/blob/main/src/Console/ConsoleScoper.php#L151) to see what you get there, I don't see why it would not be dumped otherwise

**Comment by saas786** [comment]
> > I'm not sure what could be causing this issue. Could it be due to using Windows?
> 
> I wouldn't think so, but I'm not using Windows so can't guarantee it. You could try to put a break point [here](https://github.com/humbug/php-scoper/blob/main/src/Console/ConsoleScoper.php?rgh-link-date=2024-04-18T09%3A07%3A44Z#L151) to see what you get there, I don't see why it would not be dumped otherwise

I have tested both the current dev-main and version 0.18.11.

However, they both produce the same output, and the vendor variables are null in both code bases. Could this issue be due to file path problems in Windows?

![Code_xEnX4b36LP](https://github.com/humbug/php-scoper/assets/1642796/bed54ba3-aeb7-4fb2-bd4a-67dcce0de9bd)

![0Hgw3HoZpU](https://github.com/humbug/php-scoper/assets/1642796/99c011dc-f844-4fa6-b954-8def6b412134)
